package online.mpscan.app

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.activity.enableEdgeToEdge
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.horizontalScroll
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.LazyRow
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.lazy.rememberLazyListState
import androidx.compose.foundation.lazy.grid.GridCells
import androidx.compose.foundation.lazy.grid.LazyVerticalGrid
import androidx.compose.foundation.lazy.grid.items as gridItems
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import coil3.compose.AsyncImage
import online.mpscan.app.data.CatalogRepository
import online.mpscan.app.data.Work
import online.mpscan.app.data.RecentUpdate
import online.mpscan.app.data.Chapter
import online.mpscan.app.data.OfflineStore
import online.mpscan.app.data.OfflineChapter
import online.mpscan.app.data.ReadingStore
import online.mpscan.app.data.ReadingProgress
import online.mpscan.app.data.FavoritesStore
import online.mpscan.app.data.CollectionsStore
import online.mpscan.app.data.AccountStore
import online.mpscan.app.data.WorkRating
import online.mpscan.app.data.WorkReaction
import online.mpscan.app.data.WorkSocialRepository
import online.mpscan.app.ui.theme.*
import online.mpscan.app.ui.SettingsScreen
import online.mpscan.app.ui.CommentsSection
import online.mpscan.app.ui.AccountProfileScreen
import kotlinx.coroutines.launch
import kotlinx.coroutines.flow.distinctUntilChanged
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

class MainActivity:ComponentActivity(){override fun onCreate(savedInstanceState:Bundle?){super.onCreate(savedInstanceState);enableEdgeToEdge();setContent{MpScanTheme{HomeRoot()}}}}
private enum class Destination(val label:String,val icon:String){Home("Início","⌂"),Search("Busca","⌕"),Library("Biblioteca","▣"),Profile("Perfil","♙")}

@Composable private fun HomeRoot(){
 var selected by remember{mutableStateOf(Destination.Home)};var selectedWork by remember{mutableStateOf<Work?>(null)};var directReader by remember{mutableStateOf<Pair<Work,Chapter>?>(null)};var settingsOpen by remember{mutableStateOf(false)};var works by remember{mutableStateOf<List<Work>>(emptyList())};var loading by remember{mutableStateOf(true)};var error by remember{mutableStateOf("")}
 LaunchedEffect(Unit){runCatching{CatalogRepository().works()}.onSuccess{works=it}.onFailure{error="Não foi possível carregar o catálogo."};loading=false}
 Scaffold(containerColor=MpBackground,bottomBar={if(selectedWork==null&&directReader==null&&!settingsOpen)NavigationBar(containerColor=MpSurface){Destination.entries.forEach{x->NavigationBarItem(selected=selected==x,onClick={selected=x},icon={Text(x.icon)},label={Text(x.label)})}}}){p->
  Box(Modifier.fillMaxSize().padding(p)){when{settingsOpen->SettingsScreen{settingsOpen=false};directReader!=null->Reader(directReader!!.first,directReader!!.second){directReader=null};selectedWork!=null->WorkDetails(selectedWork!!,{selectedWork=null});selected==Destination.Library->OfflineLibrary(works,{selectedWork=it}){w,c->directReader=w to c};selected==Destination.Profile->AccountProfileScreen{settingsOpen=true};loading->Box(Modifier.fillMaxSize(),contentAlignment=Alignment.Center){CircularProgressIndicator()};error.isNotBlank()->Message(error);works.isEmpty()->Message("As obras publicadas aparecerão aqui.");selected==Destination.Home->Home(works,Modifier,{selectedWork=it}){w,c->directReader=w to c};selected==Destination.Search->Search(works){selectedWork=it}}}
 }
}
@Composable private fun OfflineLibrary(works:List<Work>,openWork:(Work)->Unit,open:(Work,Chapter)->Unit){
 val context=LocalContext.current
 val store=remember{OfflineStore(context.applicationContext)}
 val readingStore=remember{ReadingStore(context.applicationContext)}
 val favorites=remember{FavoritesStore(context.applicationContext)}
 var downloads by remember{mutableStateOf(store.downloads())}
 var tab by remember{mutableStateOf("favorites")}
 val history=readingStore.history()
 Column(Modifier.fillMaxSize().padding(horizontal=16.dp)){
  Spacer(Modifier.height(16.dp));Header()
  Text("Biblioteca",fontWeight=FontWeight.Black,style=MaterialTheme.typography.headlineLarge,modifier=Modifier.padding(top=28.dp))
  Row(Modifier.padding(vertical=16.dp).horizontalScroll(rememberScrollState()),horizontalArrangement=Arrangement.spacedBy(8.dp)){
   FilterChip(tab=="favorites",{tab="favorites"},{Text("Favoritos")})
   FilterChip(tab=="collections",{tab="collections"},{Text("Coleções")})
   FilterChip(tab=="downloads",{tab="downloads"},{Text("Downloads")})
   FilterChip(tab=="continue",{tab="continue"},{Text("Continuar lendo")})
   FilterChip(tab=="history",{tab="history"},{Text("Histórico")})
  }
  if(tab=="favorites"){
   val list=works.filter{favorites.contains(it.id)}
   if(list.isEmpty())LibraryEmpty("Você ainda não favoritou nenhuma obra","Use o botão Favoritar na tela da obra.")
   else LazyVerticalGrid(GridCells.Adaptive(140.dp),horizontalArrangement=Arrangement.spacedBy(12.dp),verticalArrangement=Arrangement.spacedBy(18.dp)){gridItems(list,key={it.id}){Card(it,openWork)}}
  }else if(tab=="collections") CollectionsPanel(works,openWork)
  else if(tab=="downloads"){
   val groups=downloads.groupBy{it.workId}.values.toList()
   if(groups.isEmpty())LibraryEmpty("Nenhuma obra baixada","Abra uma obra e use Baixar todos os capítulos.")
   else LazyColumn(verticalArrangement=Arrangement.spacedBy(10.dp),contentPadding=PaddingValues(bottom=24.dp)){items(groups,key={it.first().workId}){chapters->val saved=chapters.first();val work=works.firstOrNull{it.id==saved.workId}?:saved.toWork();DownloadedWorkRow(work,chapters.size){openWork(work)}}}
  }else if(tab=="continue") ProgressList(history.filter{it.percent<100}.distinctBy{it.workId},open,"Nenhuma leitura em andamento.")
  else ProgressList(history,open,"Seu histórico ainda está vazio.")
 }
}
@Composable private fun CollectionsPanel(works:List<Work>,openWork:(Work)->Unit){val context=LocalContext.current;val store=remember{CollectionsStore(context.applicationContext)};var names by remember{mutableStateOf(store.names())};var selected by remember{mutableStateOf<String?>(null)};var dialog by remember{mutableStateOf(false)};var rename by remember{mutableStateOf(false)};var input by remember{mutableStateOf("")};var members by remember(selected){mutableStateOf(selected?.let(store::works)?:emptySet())};if(dialog)AlertDialog(onDismissRequest={dialog=false},title={Text(if(rename)"Renomear coleção" else "Nova coleção")},text={OutlinedTextField(input,{input=it},singleLine=true,label={Text("Nome")})},confirmButton={TextButton({val current=selected;if(rename&&current!=null){if(store.rename(current,input)){selected=input.trim();names=store.names()}}else if(store.create(input)){names=store.names()};dialog=false}){Text("Salvar")}},dismissButton={TextButton({dialog=false}){Text("Cancelar")}});if(selected==null){Column{Button({input="";rename=false;dialog=true},shape=RoundedCornerShape(14.dp)){Text("＋ Criar coleção")};Spacer(Modifier.height(12.dp));if(names.isEmpty())LibraryEmpty("Nenhuma coleção criada","Crie coleções para organizar suas obras.")else LazyColumn(verticalArrangement=Arrangement.spacedBy(10.dp)){items(names,key={it}){name->Surface(Modifier.fillMaxWidth().clickable{selected=name;members=store.works(name)},color=MpSurface,shape=RoundedCornerShape(16.dp),border=androidx.compose.foundation.BorderStroke(1.dp,MpLine)){Row(Modifier.padding(16.dp),verticalAlignment=Alignment.CenterVertically){Text("▣",color=MpAccent);Column(Modifier.weight(1f).padding(horizontal=12.dp)){Text(name,fontWeight=FontWeight.Bold);Text("${store.works(name).size} obras",color=MpMuted,style=MaterialTheme.typography.bodySmall)};TextButton({store.delete(name);names=store.names()}){Text("Excluir")}}}}}}}else Column{Row(verticalAlignment=Alignment.CenterVertically){TextButton({selected=null}){Text("← Voltar")};Text(selected!!,fontWeight=FontWeight.Black,modifier=Modifier.weight(1f));TextButton({input=selected!!;rename=true;dialog=true}){Text("Renomear")}};Text("Toque para adicionar ou remover",color=MpMuted,modifier=Modifier.padding(bottom=10.dp));LazyColumn(verticalArrangement=Arrangement.spacedBy(8.dp)){items(works,key={it.id}){work->Surface(Modifier.fillMaxWidth().clickable{store.toggle(selected!!,work.id);members=store.works(selected!!)},color=MpSurface,shape=RoundedCornerShape(14.dp)){Row(Modifier.padding(10.dp),verticalAlignment=Alignment.CenterVertically){AsyncImage(work.cover,work.title,Modifier.size(52.dp).clip(RoundedCornerShape(10.dp)),contentScale=ContentScale.Crop);Text(work.title,fontWeight=FontWeight.Bold,modifier=Modifier.weight(1f).padding(horizontal=10.dp),maxLines=1);Checkbox(work.id in members,{store.toggle(selected!!,work.id);members=store.works(selected!!)})}}}}}}
@Composable private fun LibraryEmpty(title:String,body:String){Surface(Modifier.fillMaxWidth(),color=MpSurface,shape=RoundedCornerShape(22.dp),border=androidx.compose.foundation.BorderStroke(1.dp,MpLine)){Column(Modifier.padding(24.dp),horizontalAlignment=Alignment.CenterHorizontally){Text("▣",color=MpAccent,style=MaterialTheme.typography.displaySmall);Text(title,fontWeight=FontWeight.Bold,modifier=Modifier.padding(top=12.dp));Text(body,color=MpMuted)}}}
@Composable private fun ProgressList(items:List<ReadingProgress>,open:(Work,Chapter)->Unit,empty:String){if(items.isEmpty()){LibraryEmpty(empty,"As leituras realizadas aparecerão aqui.");return};LazyColumn(verticalArrangement=Arrangement.spacedBy(10.dp),contentPadding=PaddingValues(bottom=24.dp)){items(items,key={it.workId+it.chapterId}){item->ProgressRow(item){open(item.toWork(),item.toChapter())}}}}
@Composable private fun ProgressRow(item:ReadingProgress,open:()->Unit){Surface(Modifier.fillMaxWidth().clickable{open()},color=MpSurface,shape=RoundedCornerShape(18.dp),border=androidx.compose.foundation.BorderStroke(1.dp,MpLine)){Row(Modifier.padding(12.dp),verticalAlignment=Alignment.CenterVertically){AsyncImage(item.workCover,item.workTitle,Modifier.size(64.dp).clip(RoundedCornerShape(12.dp)).background(MpSurface2),contentScale=ContentScale.Crop);Column(Modifier.weight(1f).padding(start=12.dp)){Text(item.workTitle,fontWeight=FontWeight.Bold,maxLines=1,overflow=TextOverflow.Ellipsis);Text("${item.chapterLabel} • página ${item.page}/${item.totalPages}",color=MpMuted,style=MaterialTheme.typography.bodySmall);LinearProgressIndicator(progress={item.percent/100f},Modifier.fillMaxWidth().padding(top=9.dp));Text("${item.percent}% lido",color=MpAccent2,style=MaterialTheme.typography.labelSmall,modifier=Modifier.padding(top=4.dp))}}}}
@Composable private fun DownloadedRow(item:OfflineChapter,open:()->Unit,delete:()->Unit){Surface(Modifier.fillMaxWidth(),color=MpSurface,shape=RoundedCornerShape(18.dp),border=androidx.compose.foundation.BorderStroke(1.dp,MpLine)){Row(Modifier.fillMaxWidth().padding(12.dp),verticalAlignment=Alignment.CenterVertically){AsyncImage(item.workCover,item.workTitle,Modifier.size(58.dp).clip(RoundedCornerShape(12.dp)).background(MpSurface2),contentScale=ContentScale.Crop);Column(Modifier.weight(1f).padding(horizontal=12.dp).clickable{open()}){Text(item.workTitle,fontWeight=FontWeight.Bold,maxLines=1,overflow=TextOverflow.Ellipsis);Text("${item.chapterLabel} • ${item.pageCount} páginas",color=MpMuted,style=MaterialTheme.typography.bodySmall);Text("Disponível offline",color=MpAccent2,style=MaterialTheme.typography.labelSmall)};TextButton(delete){Text("Excluir")}}}}
@Composable private fun DownloadedWorkRow(work:Work,chapterCount:Int,open:()->Unit){Surface(Modifier.fillMaxWidth().clickable{open()},color=MpSurface,shape=RoundedCornerShape(18.dp),border=androidx.compose.foundation.BorderStroke(1.dp,MpLine)){Row(Modifier.fillMaxWidth().padding(12.dp),verticalAlignment=Alignment.CenterVertically){AsyncImage(work.cover,work.title,Modifier.width(72.dp).aspectRatio(3f/4f).clip(RoundedCornerShape(12.dp)).background(MpSurface2),contentScale=ContentScale.Crop);Column(Modifier.weight(1f).padding(horizontal=12.dp)){Text(work.title,fontWeight=FontWeight.Black,maxLines=2,overflow=TextOverflow.Ellipsis);Text("$chapterCount ${if(chapterCount==1)"capítulo baixado" else "capítulos baixados"}",color=MpAccent2,style=MaterialTheme.typography.bodySmall,modifier=Modifier.padding(top=4.dp));Text("Toque para abrir a página da obra",color=MpMuted,style=MaterialTheme.typography.labelSmall,modifier=Modifier.padding(top=4.dp))};Text("›",color=MpMuted,style=MaterialTheme.typography.headlineSmall)}}}
private fun OfflineChapter.toWork()=Work(workId,workTitle,"",workCover,"","","","",emptyList(),0,0)
private fun OfflineChapter.toChapter()=Chapter(chapterId,chapterLabel.substringAfter("Capítulo ").toDoubleOrNull(),"",true,0)
private fun ReadingProgress.toWork()=Work(workId,workTitle,"",workCover,"","","","",emptyList(),0,0)
private fun ReadingProgress.toChapter()=Chapter(chapterId,chapterLabel.substringAfter("Capítulo ").toDoubleOrNull(),"",true,0)
@Composable private fun Header(){Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(48.dp).clip(RoundedCornerShape(16.dp)).background(Brush.linearGradient(listOf(MpAccent,MpAccent2))),contentAlignment=Alignment.Center){Text("MP",fontWeight=FontWeight.Black)};Spacer(Modifier.width(12.dp));Column{Text("MP SCAN",fontWeight=FontWeight.Black,style=MaterialTheme.typography.titleMedium);Text("Sua próxima leitura começa aqui",color=MpMuted,style=MaterialTheme.typography.bodySmall)};Spacer(Modifier.weight(1f));Surface(shape=RoundedCornerShape(14.dp),color=MpSurface,border=androidx.compose.foundation.BorderStroke(1.dp,MpLine)){Box(Modifier.size(42.dp),contentAlignment=Alignment.Center){Text("♢")}}}}
@Composable private fun Home(works:List<Work>,modifier:Modifier,open:(Work)->Unit,continueReading:(Work,Chapter)->Unit){val context=LocalContext.current;val recent=ReadingStore(context.applicationContext).history().filter{it.percent<100}.distinctBy{it.workId}.take(10);var updates by remember(works){mutableStateOf<List<RecentUpdate>>(emptyList())};LaunchedEffect(works){updates=runCatching{CatalogRepository().recentUpdates(works)}.getOrDefault(emptyList())};LazyColumn(modifier.fillMaxSize().padding(horizontal=16.dp),contentPadding=PaddingValues(top=16.dp,bottom=32.dp),verticalArrangement=Arrangement.spacedBy(28.dp)){item{Header()};item{Hero(works.first(),open)};item{Rail("Em alta",works.sortedByDescending{it.reads}.take(10),true,open)};if(recent.isNotEmpty())item{Column{Text("Continuar lendo",fontWeight=FontWeight.Black,style=MaterialTheme.typography.headlineSmall);Spacer(Modifier.height(12.dp));LazyRow(horizontalArrangement=Arrangement.spacedBy(12.dp)){items(recent,key={it.workId}){item->Box(Modifier.width(260.dp)){ProgressRow(item){continueReading(item.toWork(),item.toChapter())}}}}}};item{RecentUpdates(updates,open)}}}
@Composable private fun Hero(w:Work,open:(Work)->Unit){Box(Modifier.fillMaxWidth().height(490.dp).clip(RoundedCornerShape(34.dp)).background(MpSurface)){AsyncImage(w.banner.ifBlank{w.cover},w.title,Modifier.fillMaxSize(),contentScale=ContentScale.Crop);Box(Modifier.fillMaxSize().background(Brush.horizontalGradient(listOf(Color(0xF207070A),Color(0xA607070A),Color.Transparent))));Box(Modifier.fillMaxSize().background(Brush.verticalGradient(listOf(Color.Transparent,Color(0xF507070A)))));Column(Modifier.align(Alignment.BottomStart).padding(26.dp).fillMaxWidth(.92f)){Text("DESTAQUE MP SCAN",color=MpAccent2,fontWeight=FontWeight.Black,style=MaterialTheme.typography.labelSmall);Spacer(Modifier.height(10.dp));Text(w.title,fontWeight=FontWeight.Black,style=MaterialTheme.typography.headlineLarge,maxLines=2,overflow=TextOverflow.Ellipsis);Text(w.synopsis,color=MpMuted,maxLines=3,overflow=TextOverflow.Ellipsis,modifier=Modifier.padding(vertical=12.dp));Button(onClick={open(w)},shape=RoundedCornerShape(14.dp)){Text("Ver detalhes",fontWeight=FontWeight.Black)}}}}
@Composable private fun Rail(title:String,works:List<Work>,ranked:Boolean,open:(Work)->Unit){Column{Text(title,fontWeight=FontWeight.Black,style=MaterialTheme.typography.headlineSmall);Spacer(Modifier.height(12.dp));LazyRow(horizontalArrangement=Arrangement.spacedBy(13.dp)){items(works,key={it.id}){w->Box{Card(w,open);if(ranked)Text((works.indexOf(w)+1).toString(),fontWeight=FontWeight.Black,style=MaterialTheme.typography.displaySmall,color=Color.White,modifier=Modifier.align(Alignment.BottomStart).background(Color(0xB30B0B0D)).padding(horizontal=8.dp))}}}}}
@Composable private fun RecentUpdates(updates:List<RecentUpdate>,open:(Work)->Unit){Column{Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text("Atualizações recentes",fontWeight=FontWeight.Black,style=MaterialTheme.typography.headlineSmall);Text("Capítulos que acabaram de chegar",color=MpMuted,style=MaterialTheme.typography.bodySmall)};Text("NOVO",color=MpAccent2,fontWeight=FontWeight.Black,style=MaterialTheme.typography.labelSmall)};Spacer(Modifier.height(14.dp));if(updates.isEmpty()){Text("As próximas atualizações aparecerão aqui.",color=MpMuted)}else updates.chunked(2).forEach{pair->Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(12.dp)){pair.forEach{update->val w=update.work;Surface(Modifier.weight(1f),color=MpSurface,shape=RoundedCornerShape(20.dp),border=androidx.compose.foundation.BorderStroke(1.dp,MpLine)){Column{Box(Modifier.fillMaxWidth().aspectRatio(3f/4f).clickable{open(w)}){AsyncImage(w.cover,w.title,Modifier.fillMaxSize(),contentScale=ContentScale.Crop);Text("NOVO",color=Color.White,fontWeight=FontWeight.Black,style=MaterialTheme.typography.labelSmall,modifier=Modifier.align(Alignment.TopStart).padding(9.dp).background(MpAccent,RoundedCornerShape(9.dp)).padding(horizontal=8.dp,vertical=4.dp))};Column(Modifier.padding(12.dp)){Text(w.title,fontWeight=FontWeight.Black,maxLines=2,overflow=TextOverflow.Ellipsis);Text(update.chapter.label,color=MpAccent2,fontWeight=FontWeight.Bold,style=MaterialTheme.typography.bodySmall,modifier=Modifier.padding(top=6.dp));if(update.chapter.title.isNotBlank())Text(update.chapter.title,color=MpMuted,style=MaterialTheme.typography.bodySmall,maxLines=1,overflow=TextOverflow.Ellipsis);Text(formatUpdateDate(update.updatedAt),color=MpMuted,style=MaterialTheme.typography.labelSmall,modifier=Modifier.padding(top=3.dp));Button(onClick={open(w)},modifier=Modifier.fillMaxWidth().padding(top=10.dp),shape=RoundedCornerShape(12.dp),contentPadding=PaddingValues(vertical=8.dp)){Text("LER AGORA",fontWeight=FontWeight.Black,style=MaterialTheme.typography.labelMedium)}}}}};if(pair.size==1)Spacer(Modifier.weight(1f))};Spacer(Modifier.height(12.dp))}}}
private fun formatUpdateDate(value:Long):String{if(value<=0)return "Atualização recente";val millis=if(value<100000000000L)value*1000 else value;return SimpleDateFormat("dd/MM/yyyy",Locale("pt","BR")).format(Date(millis))}
@Composable private fun Card(w:Work,open:(Work)->Unit){Column(Modifier.width(148.dp).clickable{open(w)}){AsyncImage(w.cover,w.title,Modifier.fillMaxWidth().aspectRatio(3f/4f).clip(RoundedCornerShape(18.dp)).background(MpSurface2),contentScale=ContentScale.Crop);Text(w.title,fontWeight=FontWeight.Bold,maxLines=1,overflow=TextOverflow.Ellipsis,modifier=Modifier.padding(top=8.dp));Text(w.type,color=MpMuted,style=MaterialTheme.typography.bodySmall)}}
@Composable private fun Search(works:List<Work>,open:(Work)->Unit){
 var query by remember{mutableStateOf("")};var status by remember{mutableStateOf("")};var genre by remember{mutableStateOf("")}
 val genres=remember(works){works.flatMap{it.genres}.distinct().sorted()}
 val filtered=remember(works,query,status,genre){works.filter{w->(query.isBlank()||(w.title+" "+w.author+" "+w.genres.joinToString()).contains(query,true))&&(status.isBlank()||localizedStatus(w.status).equals(status,true))&&(genre.isBlank()||w.genres.any{it.equals(genre,true)})}}
 Column(Modifier.fillMaxSize().padding(horizontal=16.dp,vertical=14.dp)){Header();Spacer(Modifier.height(18.dp));OutlinedTextField(query,{query=it},Modifier.fillMaxWidth(),singleLine=true,shape=RoundedCornerShape(16.dp),leadingIcon={Text("⌕")},label={Text("Nome, gênero ou autor")});LazyRow(Modifier.padding(vertical=12.dp),horizontalArrangement=Arrangement.spacedBy(8.dp)){item{FilterChip(status.isBlank(),{status=""},{Text("Todos")})};items(listOf("Em andamento","Completa","Em pausa","Futura","Cancelada")){s->FilterChip(status==s,{status=if(status==s)"" else s},{Text(s)})}};if(genres.isNotEmpty())LazyRow(horizontalArrangement=Arrangement.spacedBy(8.dp)){items(genres){g->FilterChip(genre==g,{genre=if(genre==g)"" else g},{Text(g)})}};Text("${filtered.size} obras",color=MpMuted,modifier=Modifier.padding(vertical=10.dp));LazyVerticalGrid(GridCells.Adaptive(140.dp),horizontalArrangement=Arrangement.spacedBy(12.dp),verticalArrangement=Arrangement.spacedBy(18.dp)){gridItems(filtered,key={it.id}){Card(it,open)}}}
}
@Composable private fun WorkDetails(work:Work,back:()->Unit){
 val context=LocalContext.current;val favorites=remember{FavoritesStore(context.applicationContext)};val readingStore=remember{ReadingStore(context.applicationContext)};val offlineStore=remember{OfflineStore(context.applicationContext)};val repository=remember{CatalogRepository()};val social=remember{WorkSocialRepository()};val session=remember{AccountStore(context.applicationContext).session()};val scope=rememberCoroutineScope()
 var favorite by remember(work.id){mutableStateOf(favorites.contains(work.id))};var chapters by remember(work.id){mutableStateOf<List<Chapter>>(emptyList())};var loading by remember(work.id){mutableStateOf(true)};var reading by remember(work.id){mutableStateOf<Chapter?>(null)}
 var tab by remember(work.id){mutableStateOf("Capítulos")};var rating by remember(work.id){mutableStateOf(WorkRating())};var reactions by remember(work.id){mutableStateOf<List<WorkReaction>>(emptyList())};var socialError by remember{mutableStateOf("")}
 var downloadingAll by remember(work.id){mutableStateOf(false)};var bulkProgress by remember(work.id){mutableIntStateOf(0)};var bulkMessage by remember(work.id){mutableStateOf("")};var bulkError by remember(work.id){mutableStateOf("")}
 if(reading!=null){Reader(work,reading!!){reading=null};return}
 LaunchedEffect(work.id){val saved=offlineStore.downloads().filter{it.workId==work.id}.map{it.toChapter()};runCatching{repository.chapters(work.id)}.onSuccess{remote->chapters=(remote+saved).distinctBy{it.id}.sortedByDescending{it.number?:-1.0}}.onFailure{chapters=saved};rating=runCatching{social.rating(work.id,session)}.getOrDefault(WorkRating());reactions=runCatching{social.reactions(work.id,session)}.getOrDefault(emptyList());loading=false}
 val progress=remember(work.id,chapters){readingStore.history().filter{it.workId==work.id}.associateBy{it.chapterId}}
 val continueChapter=chapters.firstOrNull{(progress[it.id]?.percent?:0)<100}?:chapters.firstOrNull()
 val knownAdmin=session?.uid in setOf("eHLv7TlUOAW5rLsMwWVCGeu1KSI2","pc87zkEpz0Ra7HfKvRIwLkbl5K13")||session?.email in setOf("meowscann@gmail.com","mpscan@gmail.com")
 LazyColumn(Modifier.fillMaxSize(),contentPadding=PaddingValues(bottom=30.dp)){
  item{WorkHero(work,chapters.size,rating.average,back)}
  item{Column(Modifier.padding(horizontal=12.dp,vertical=14.dp)){Button({continueChapter?.let{reading=it}},Modifier.fillMaxWidth().height(58.dp),enabled=continueChapter!=null,shape=RoundedCornerShape(17.dp)){Text(if(progress.isNotEmpty())"▶ Continuar lendo" else "▶ Começar a ler",fontWeight=FontWeight.Black)};Row(Modifier.padding(top=10.dp),horizontalArrangement=Arrangement.spacedBy(10.dp)){OutlinedButton({favorite=favorites.toggle(work.id)}){Text(if(favorite)"♥" else "♡")};OutlinedButton({}){Text("♢")};OutlinedButton({}){Text("＋")}}}}
  if(reactions.isNotEmpty())item{WorkReactions(reactions){chosen->if(session==null){socialError="Entre na conta para escolher uma reação."}else scope.launch{runCatching{social.react(work.id,chosen,session)}.onSuccess{reactions=social.reactions(work.id,session);socialError=""}.onFailure{socialError="Não foi possível salvar sua reação."}}}}
  item{RatingPanel(rating,knownAdmin,session!=null){note->if(session==null)socialError="Entre na conta para avaliar." else scope.launch{runCatching{social.rate(work.id,note,session)}.onSuccess{rating=social.rating(work.id,session);socialError=""}.onFailure{socialError="Esta conta não pode avaliar ou ocorreu um erro."}}}}
  if(socialError.isNotBlank())item{Text(socialError,color=MaterialTheme.colorScheme.error,modifier=Modifier.padding(horizontal=16.dp,vertical=8.dp))}
  item{WorkTabs(tab,chapters.size){tab=it}}
  when(tab){
   "Sobre"->{item{SynopsisCard(work)};item{WorkInformation(work,chapters.firstOrNull()?.updatedAt?:work.updatedAt)}}
   "Comentários"->item{CommentsSection("obra",work.id,"",Modifier.padding(horizontal=12.dp,vertical=18.dp))}
   else->{item{Column(Modifier.padding(horizontal=12.dp,vertical=10.dp)){Button(onClick={scope.launch{if(chapters.isEmpty())return@launch;downloadingAll=true;bulkError="";bulkMessage="Preparando downloads…";val pending=chapters.filter{offlineStore.localPages(work.id,it.id).isEmpty()};if(pending.isEmpty()){bulkProgress=100;bulkMessage="Todos os capítulos já estão baixados."}else{var completed=0;for(chapter in pending){bulkMessage="Baixando ${chapter.label}";val result=runCatching{val pages=repository.pages(work.id,chapter.id);offlineStore.download(work,chapter,pages){pageProgress->bulkProgress=((completed*100)+pageProgress)/pending.size}};if(result.isFailure){bulkError="Alguns capítulos não puderam ser baixados.";break};completed++;bulkProgress=(completed*100)/pending.size};if(bulkError.isBlank())bulkMessage="Download concluído."};downloadingAll=false}},enabled=!loading&&!downloadingAll&&chapters.isNotEmpty(),modifier=Modifier.fillMaxWidth(),shape=RoundedCornerShape(15.dp)){Text(if(downloadingAll)"Baixando… $bulkProgress%" else "⇣ Baixar todos os capítulos",fontWeight=FontWeight.Black)};if(downloadingAll)LinearProgressIndicator(progress={bulkProgress/100f},modifier=Modifier.fillMaxWidth().padding(top=8.dp));if(bulkMessage.isNotBlank())Text(bulkMessage,color=if(bulkError.isBlank())MpAccent2 else MaterialTheme.colorScheme.error,modifier=Modifier.padding(top=7.dp))}};if(loading)item{LinearProgressIndicator(Modifier.fillMaxWidth().padding(horizontal=16.dp))};items(chapters,key={it.id}){c->ChapterRow(c,progress[c.id],offlineStore.localPages(work.id,c.id).isNotEmpty()){reading=c}}}
  }
 }
}
@Composable private fun WorkHero(work:Work,chapterCount:Int,average:Double,back:()->Unit){Box(Modifier.fillMaxWidth().height(520.dp)){AsyncImage(work.banner.ifBlank{work.cover},work.title,Modifier.fillMaxSize(),contentScale=ContentScale.Crop);Box(Modifier.fillMaxSize().background(Brush.verticalGradient(listOf(Color(0x22000000),Color(0xAA08080B),MpBackground))));FilledTonalButton(back,Modifier.padding(18.dp)){Text("←")};Surface(Modifier.align(Alignment.TopEnd).padding(18.dp),shape=RoundedCornerShape(18.dp),color=Color(0x990B0B0D)){Text("↗",Modifier.padding(14.dp),fontWeight=FontWeight.Black)};Row(Modifier.align(Alignment.BottomStart).padding(18.dp),verticalAlignment=Alignment.Bottom){AsyncImage(work.cover,work.title,Modifier.width(140.dp).aspectRatio(3f/4f).clip(RoundedCornerShape(20.dp)),contentScale=ContentScale.Crop);Column(Modifier.weight(1f).padding(start=16.dp,bottom=4.dp)){Text("MP SCAN • OBRA",color=MpMuted,fontWeight=FontWeight.Black,style=MaterialTheme.typography.labelSmall);Text(work.title,fontWeight=FontWeight.Black,style=MaterialTheme.typography.headlineMedium,maxLines=3,overflow=TextOverflow.Ellipsis);if(work.alternateTitle.isNotBlank())Text(work.alternateTitle,color=MpMuted,maxLines=2,modifier=Modifier.padding(top=5.dp));LazyRow(Modifier.padding(top=12.dp),horizontalArrangement=Arrangement.spacedBy(7.dp)){item{WorkPill("★ ${"%.1f".format(Locale.US,average)}")};item{WorkPill(localizedStatus(work.status))};item{WorkPill("$chapterCount capítulos")}}}}}}
@Composable private fun WorkPill(text:String){Surface(color=MpSurface.copy(.9f),shape=RoundedCornerShape(18.dp),border=androidx.compose.foundation.BorderStroke(1.dp,MpLine)){Text(text,Modifier.padding(horizontal=12.dp,vertical=7.dp),style=MaterialTheme.typography.bodySmall)}}
@Composable private fun WorkReactions(items:List<WorkReaction>,choose:(WorkReaction)->Unit){Surface(Modifier.fillMaxWidth().padding(horizontal=12.dp,vertical=8.dp),color=MpSurface,shape=RoundedCornerShape(24.dp),border=androidx.compose.foundation.BorderStroke(1.dp,Color(0xff57253d))){Column(Modifier.padding(18.dp)){Text("✨ Qual foi sua reação?",fontWeight=FontWeight.Black,style=MaterialTheme.typography.titleLarge);Text("Escolha uma reação criada pela equipe para esta obra.",color=MpMuted,modifier=Modifier.padding(top=4.dp,bottom=14.dp));LazyRow(horizontalArrangement=Arrangement.spacedBy(10.dp)){items(items,key={it.source+it.id}){reaction->Surface(Modifier.width(132.dp).clickable{choose(reaction)},color=if(reaction.selected)Color(0xff2b1622)else MpSurface2,shape=RoundedCornerShape(20.dp),border=androidx.compose.foundation.BorderStroke(if(reaction.selected)2.dp else 1.dp,if(reaction.selected)MpAccent2 else MpLine)){Column(Modifier.padding(12.dp),horizontalAlignment=Alignment.CenterHorizontally){if(reaction.image.isNotBlank())AsyncImage(reaction.image,reaction.label,Modifier.size(66.dp),contentScale=ContentScale.Fit);Text(reaction.label,fontWeight=FontWeight.Bold,maxLines=2,overflow=TextOverflow.Ellipsis,modifier=Modifier.padding(top=8.dp));if(reaction.source=="global")Text("PARA TODOS",color=MpAccent2,style=MaterialTheme.typography.labelSmall,modifier=Modifier.padding(top=8.dp));Text(if(reaction.selected)"Sua reação • ${reaction.votes} votos" else "${reaction.votes} votos",color=MpMuted,style=MaterialTheme.typography.labelSmall,modifier=Modifier.padding(top=7.dp))}}}}}}
@Composable private fun RatingPanel(rating:WorkRating,admin:Boolean,logged:Boolean,rate:(Int)->Unit){Surface(Modifier.fillMaxWidth().padding(horizontal=12.dp,vertical=8.dp),color=Color(0xff18171d),shape=RoundedCornerShape(24.dp),border=androidx.compose.foundation.BorderStroke(1.dp,Color(0xff715a2a))){Column(Modifier.padding(20.dp)){Text("AVALIAÇÃO DOS LEITORES",color=Color(0xffff6e9c),fontWeight=FontWeight.Black,style=MaterialTheme.typography.labelMedium);Row(verticalAlignment=Alignment.Bottom){Text("${"%.1f".format(Locale.US,rating.average)}",fontWeight=FontWeight.Black,style=MaterialTheme.typography.displayMedium);Text("★",color=Color(0xffffc13d),style=MaterialTheme.typography.headlineMedium,modifier=Modifier.padding(bottom=8.dp))};Text("${rating.total} ${if(rating.total==1)"avaliação" else "avaliações"} no total",color=MpMuted);Spacer(Modifier.height(14.dp));for(note in 5 downTo 1){val count=rating.counts[note]?:0;val part=if(rating.total==0)0f else count.toFloat()/rating.total;Row(Modifier.fillMaxWidth().padding(vertical=4.dp),verticalAlignment=Alignment.CenterVertically){Text("$note★",Modifier.width(42.dp));LinearProgressIndicator(progress={part},Modifier.weight(1f),color=Color(0xffffc13d),trackColor=MpSurface2);Text("$count",Modifier.width(32.dp),textAlign=androidx.compose.ui.text.style.TextAlign.End,color=MpMuted)}};HorizontalDivider(Modifier.padding(vertical=16.dp),color=MpLine);Text("Avaliações dos leitores",fontWeight=FontWeight.Bold,style=MaterialTheme.typography.titleMedium);Text(if(admin)"A conta ADM visualiza as notas, mas não participa da avaliação." else if(logged)"Toque em uma estrela para avaliar. Você pode mudar quando quiser." else "Entre na conta para participar da avaliação.",color=MpMuted,style=MaterialTheme.typography.bodySmall);Row(Modifier.padding(top=12.dp),horizontalArrangement=Arrangement.spacedBy(9.dp)){for(note in 1..5){OutlinedButton({rate(note)},enabled=logged&&!admin,contentPadding=PaddingValues(0.dp),modifier=Modifier.size(52.dp),border=androidx.compose.foundation.BorderStroke(1.dp,if(note<=rating.mine)Color(0xffffc13d)else MpLine)){Text("★",color=if(note<=rating.mine)Color(0xffffc13d)else MpMuted)}}}}}}
@Composable private fun WorkTabs(selected:String,count:Int,change:(String)->Unit){Row(Modifier.fillMaxWidth().padding(horizontal=12.dp,vertical=12.dp).clip(RoundedCornerShape(20.dp)).background(MpSurface2).padding(5.dp),horizontalArrangement=Arrangement.spacedBy(5.dp)){listOf("Sobre","Capítulos","Comentários").forEach{name->Surface(Modifier.weight(1f).clickable{change(name)},color=if(selected==name)Color(0xff2b1822)else Color.Transparent,shape=RoundedCornerShape(15.dp)){Column(Modifier.padding(vertical=12.dp),horizontalAlignment=Alignment.CenterHorizontally){Text(if(name=="Capítulos")"Capítulos $count" else name,fontWeight=FontWeight.Bold,color=if(selected==name)Color.White else MpMuted);if(selected==name)Box(Modifier.padding(top=7.dp).width(58.dp).height(3.dp).background(MpAccent2,RoundedCornerShape(2.dp)))}}}}}
@Composable private fun SynopsisCard(work:Work){Surface(Modifier.fillMaxWidth().padding(horizontal=12.dp,vertical=8.dp),color=MpSurface,shape=RoundedCornerShape(24.dp),border=androidx.compose.foundation.BorderStroke(1.dp,MpLine)){Column(Modifier.padding(20.dp)){Text("SINOPSE",color=MpAccent2,fontWeight=FontWeight.Black,style=MaterialTheme.typography.labelMedium);Text(work.synopsis.ifBlank{"Sinopse ainda não informada."},modifier=Modifier.padding(top=14.dp),lineHeight=28.sp);if(work.genres.isNotEmpty())LazyRow(Modifier.padding(top=18.dp),horizontalArrangement=Arrangement.spacedBy(8.dp)){items(work.genres){genre->Surface(color=Color(0xff2a1720),shape=RoundedCornerShape(18.dp),border=androidx.compose.foundation.BorderStroke(1.dp,Color(0xff5b2b42))){Text(genre,Modifier.padding(horizontal=14.dp,vertical=8.dp),fontWeight=FontWeight.Bold)}}}}}}
@Composable
private fun WorkInformation(work: Work, lastUpdate: Long) {
    val rows = listOf(
        "TIPO" to localizedType(work.type),
        "STATUS" to localizedStatus(work.status),
        "AGENDA" to work.schedule,
        "ÚLTIMA ATUALIZAÇÃO" to formatWorkDate(lastUpdate),
        "AUTOR" to work.author,
        "ARTISTA" to work.artist,
        "SCAN" to work.scan,
        "IDIOMA" to work.language
    ).filter { it.second.isNotBlank() }
    Column(Modifier.padding(horizontal = 12.dp, vertical = 4.dp)) {
        rows.forEach { (label, value) ->
            Surface(
                Modifier.fillMaxWidth().padding(vertical = 6.dp),
                color = MpSurface,
                shape = RoundedCornerShape(20.dp),
                border = androidx.compose.foundation.BorderStroke(
                    1.dp,
                    if (label == "ÚLTIMA ATUALIZAÇÃO") Color(0xff62263f) else MpLine
                )
            ) {
                Column(Modifier.padding(18.dp)) {
                    Text(label, color = MpMuted, fontWeight = FontWeight.Black, style = MaterialTheme.typography.labelSmall)
                    Text(
                        value.ifBlank { "—" },
                        fontWeight = FontWeight.SemiBold,
                        style = MaterialTheme.typography.titleMedium,
                        modifier = Modifier.padding(top = 3.dp)
                    )
                }
            }
        }
    }
}
@Composable private fun ChapterRow(chapter:Chapter,progress:ReadingProgress?,saved:Boolean,open:()->Unit){val fresh=System.currentTimeMillis()-normalizeMillis(maxOf(chapter.updatedAt,chapter.createdAt))<14L*24*60*60*1000;Surface(Modifier.fillMaxWidth().padding(horizontal=12.dp,vertical=6.dp).clickable{open()},color=MpSurface,shape=RoundedCornerShape(20.dp),border=androidx.compose.foundation.BorderStroke(1.dp,if((progress?.percent?:0)>0)Color(0xff245944)else MpLine)){Row(Modifier.padding(14.dp),verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(58.dp).clip(RoundedCornerShape(17.dp)).background(Color(0xff261722)),contentAlignment=Alignment.Center){Text(chapter.number?.toString()?.removeSuffix(".0")?:"—",color=MpAccent2,fontWeight=FontWeight.Black,style=MaterialTheme.typography.titleLarge)};Column(Modifier.weight(1f).padding(horizontal=14.dp)){Text(if(chapter.title.isBlank())chapter.label else chapter.title,fontWeight=FontWeight.Black,style=MaterialTheme.typography.titleMedium);Row(horizontalArrangement=Arrangement.spacedBy(7.dp),verticalAlignment=Alignment.CenterVertically){Text(formatWorkDate(maxOf(chapter.updatedAt,chapter.createdAt)),color=MpMuted,style=MaterialTheme.typography.bodySmall);if(fresh)Text("NOVO",color=MpAccent2,fontWeight=FontWeight.Black,style=MaterialTheme.typography.labelSmall);if(progress!=null)Text(if(progress.percent>=100)"● LIDO" else "● LENDO ${progress.percent}%",color=Color(0xff32bd84),fontWeight=FontWeight.Black,style=MaterialTheme.typography.labelSmall);if(saved)Text("OFFLINE",color=MpAccent,style=MaterialTheme.typography.labelSmall)}};Text("›",style=MaterialTheme.typography.headlineSmall)}}}
private fun localizedType(value:String)=when(value.trim().lowercase(Locale.ROOT)){"manga","mangá"->"Mangá";"manhwa"->"Manhwa";"manhua"->"Manhua";"novel"->"Novel";"webtoon"->"Webtoon";"oneshot","one-shot"->"One-shot";"hq"->"HQ";else->value.ifBlank{"—"}}
private fun normalizeMillis(value:Long)=if(value in 1..99_999_999_999L)value*1000 else value
private fun formatWorkDate(value:Long)=if(value<=0)"—" else SimpleDateFormat("dd/MM/yyyy",Locale("pt","BR")).format(Date(normalizeMillis(value)))
private fun localizedStatus(value:String):String=when(value.trim().lowercase(Locale.ROOT).replace("_"," ").replace("-"," ")){
 "ongoing","in progress","andamento","em andamento"->"Em andamento"
 "completed","complete","completo","completa","finalizado","finalizada"->"Completa"
 "hiatus","paused","pause","em pausa","pausado","pausada"->"Em pausa"
 "future","upcoming","futuro","futura"->"Futura"
 "cancelled","canceled","cancelado","cancelada"->"Cancelada"
 else->value.ifBlank{"Status não informado"}
}
@Composable private fun Reader(work:Work,chapter:Chapter,back:()->Unit){
 val context=LocalContext.current;val store=remember{OfflineStore(context.applicationContext)};val readingStore=remember{ReadingStore(context.applicationContext)};val scope=rememberCoroutineScope();val listState=rememberLazyListState()
 var current by remember(work.id,chapter.id){mutableStateOf(chapter)}
 var chapters by remember(work.id){mutableStateOf<List<Chapter>>(emptyList())}
 var listOpen by remember{mutableStateOf(false)}
 var pages by remember(current.id){mutableStateOf<List<String>>(emptyList())};var remotePages by remember(current.id){mutableStateOf<List<String>>(emptyList())};var loading by remember(current.id){mutableStateOf(true)};var failed by remember(current.id){mutableStateOf(false)};var offline by remember(current.id){mutableStateOf(false)};var downloading by remember(current.id){mutableStateOf(false)};var progress by remember(current.id){mutableIntStateOf(0)};var downloadError by remember(current.id){mutableStateOf("")}
 LaunchedEffect(work.id){val saved=store.downloads().filter{it.workId==work.id}.map{it.toChapter()};chapters=runCatching{(CatalogRepository().chapters(work.id)+saved).distinctBy{it.id}.sortedBy{it.number?:Double.MAX_VALUE}}.getOrDefault(saved.sortedBy{it.number?:Double.MAX_VALUE});if(chapters.none{it.id==current.id})chapters=(chapters+current).distinctBy{it.id}.sortedBy{it.number?:Double.MAX_VALUE}}
 LaunchedEffect(current.id){val saved=store.localPages(work.id,current.id);if(saved.isNotEmpty()){pages=saved;offline=true;loading=false}else{runCatching{CatalogRepository().pages(work.id,current.id)}.onSuccess{remotePages=it;pages=it}.onFailure{failed=true};loading=false};if(pages.isNotEmpty()){val last=readingStore.progress(work.id,current.id)?.page?.minus(1)?.coerceIn(0,pages.lastIndex)?:0;listState.scrollToItem(last)}}
 LaunchedEffect(listState,pages.size,current.id){if(pages.isNotEmpty())snapshotFlow{listState.firstVisibleItemIndex}.distinctUntilChanged().collect{index->readingStore.save(work,current,index+1,pages.size)}}
 val position=chapters.indexOfFirst{it.id==current.id};val previous=chapters.getOrNull(position-1);val next=chapters.getOrNull(position+1)
 if(listOpen)ChapterListDialog(chapters,current.id,store,work.id,{listOpen=false}){current=it;listOpen=false}
 Column(Modifier.fillMaxSize().background(Color(0xFF050507))){Row(Modifier.fillMaxWidth().background(Color(0xEE0B0B0D)).padding(8.dp),verticalAlignment=Alignment.CenterVertically){FilledTonalButton(back){Text("←")};Column(Modifier.weight(1f).padding(horizontal=12.dp)){Text(work.title,fontWeight=FontWeight.Bold,maxLines=1,overflow=TextOverflow.Ellipsis);Text(if(offline) "${current.label} • salvo offline" else current.label,color=if(offline)MpAccent2 else MpMuted,style=MaterialTheme.typography.bodySmall)};TextButton({listOpen=true}){Text("☰ Capítulos")};if(!offline&&pages.isNotEmpty())Button(onClick={scope.launch{downloading=true;downloadError="";runCatching{store.download(work,current,remotePages.ifEmpty{pages}){progress=it}}.onSuccess{pages=it;offline=true}.onFailure{downloadError="Não foi possível concluir o download."};downloading=false}},enabled=!downloading,shape=RoundedCornerShape(12.dp)){Text(if(downloading)"$progress%" else "Baixar")}}
  if(downloading)LinearProgressIndicator(progress={progress/100f},Modifier.fillMaxWidth())
  if(downloadError.isNotBlank())Text(downloadError,color=MaterialTheme.colorScheme.error,modifier=Modifier.padding(12.dp))
  when{loading->Box(Modifier.fillMaxSize(),contentAlignment=Alignment.Center){CircularProgressIndicator()};failed->Message("Este capítulo não está baixado. Conecte-se à internet ou escolha um capítulo marcado como OFFLINE.");pages.isEmpty()->Message("Nenhuma página encontrada.");else->LazyColumn(Modifier.fillMaxSize(),state=listState,horizontalAlignment=Alignment.CenterHorizontally){items(pages){page->AsyncImage(page,null,Modifier.fillMaxWidth(),contentScale=ContentScale.FillWidth)};item{CommentsSection("capitulo",work.id,current.id,Modifier.fillMaxWidth().padding(16.dp))};item{ChapterNavigation(previous,next,{listOpen=true}){current=it}}}}
 }
}
@Composable private fun ChapterNavigation(previous:Chapter?,next:Chapter?,openList:()->Unit,open:(Chapter)->Unit){
 Surface(Modifier.fillMaxWidth().padding(16.dp),color=MpSurface,shape=RoundedCornerShape(20.dp),border=androidx.compose.foundation.BorderStroke(1.dp,MpLine)){Column(Modifier.padding(14.dp)){Text("Continuar leitura",fontWeight=FontWeight.Black,style=MaterialTheme.typography.titleMedium);Row(Modifier.fillMaxWidth().padding(top=12.dp),horizontalArrangement=Arrangement.spacedBy(8.dp)){OutlinedButton({previous?.let(open)},Modifier.weight(1f),enabled=previous!=null){Text("← Anterior")};Button(openList,Modifier.weight(1f)){Text("☰ Lista")};OutlinedButton({next?.let(open)},Modifier.weight(1f),enabled=next!=null){Text("Próximo →")}}}}
}
@Composable private fun ChapterListDialog(chapters:List<Chapter>,selectedId:String,store:OfflineStore,workId:String,close:()->Unit,open:(Chapter)->Unit){
 AlertDialog(onDismissRequest=close,title={Text("Lista de capítulos")},text={if(chapters.isEmpty())Text("Nenhum capítulo disponível offline.",color=MpMuted)else LazyColumn(Modifier.heightIn(max=480.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){items(chapters,key={it.id}){item->val saved=store.localPages(workId,item.id).isNotEmpty();Surface(Modifier.fillMaxWidth().clickable{open(item)},color=if(item.id==selectedId)MpAccent.copy(.18f)else MpSurface2,shape=RoundedCornerShape(14.dp),border=androidx.compose.foundation.BorderStroke(1.dp,if(item.id==selectedId)MpAccent else MpLine)){Row(Modifier.padding(13.dp),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(item.label,fontWeight=FontWeight.Bold);if(item.title.isNotBlank())Text(item.title,color=MpMuted,style=MaterialTheme.typography.bodySmall)};if(saved)Text("OFFLINE",color=MpAccent2,fontWeight=FontWeight.Black,style=MaterialTheme.typography.labelSmall)}}}}},confirmButton={TextButton(close){Text("Fechar")}})
}
@Composable private fun Message(text:String){Box(Modifier.fillMaxSize().padding(24.dp),contentAlignment=Alignment.Center){Text(text,color=MpMuted)}}
