 if(current==null)Column{Button({creating=true},shape=RoundedCornerShape(14.dp)){Text("＋ Criar coleção")};Spacer(Modifier.height(12.dp));when{loading->CircularProgressIndicator();error.isNotBlank()->LibraryEmpty("Coleções indisponíveis",error);collections.isEmpty()->LibraryEmpty("Nenhuma coleção criada","Crie uma coleção aqui e adicione obras pelo botão ＋ dentro da obra.");else->LazyColumn(verticalArrangement=Arrangement.spacedBy(10.dp)){items(collections,key={it.id}){item->Surface(Modifier.fillMaxWidth().clickable{selected=item},color=MpSurface,shape=RoundedCornerShape(16.dp),border=androidx.compose.foundation.BorderStroke(1.dp,MpLine)){Row(Modifier.padding(16.dp),verticalAlignment=Alignment.CenterVertically){Text(if(item.isPublic)"🌐" else "🔒");Column(Modifier.weight(1f).padding(horizontal=12.dp)){Text(item.name,fontWeight=FontWeight.Bold);Text("${item.workIds.size} obras • ${if(item.isPublic)"Pública" else "Privada"}",color=MpMuted,style=MaterialTheme.typography.bodySmall)};Text("›",color=MpMuted)}}}}}}else Column{Row(verticalAlignment=Alignment.CenterVertically){TextButton({selected=null}){Text("← Voltar")};Column{Text(current.name,fontWeight=FontWeight.Black);Text(if(current.isPublic)"🌐 Coleção pública" else "🔒 Coleção privada",color=MpMuted,style=MaterialTheme.typography.bodySmall)}};Text("Para adicionar ou remover, abra a obra e toque no botão ＋.",color=MpMuted,modifier=Modifier.padding(vertical=10.dp));val members=works.filter{it.id in current.workIds};if(members.isEmpty())LibraryEmpty("Coleção vazia","Use o botão ＋ na página de uma obra.")else LazyVerticalGrid(GridCells.Adaptive(140.dp),horizontalArrangement=Arrangement.spacedBy(12.dp),verticalArrangement=Arrangement.spacedBy(18.dp)){gridItems(members,key={it.id}){Card(it,openWork)}}}
}
@Composable private fun LibraryEmpty(title:String,body:String){Surface(Modifier.fillMaxWidth(),color=MpSurface,shape=RoundedCornerShape(22.dp),border=androidx.compose.foundation.BorderStroke(1.dp,MpLine)){Column(Modifier.padding(24.dp),horizontalAlignment=Alignment.CenterHorizontally){Text("▣",color=MpAccent,style=MaterialTheme.typography.displaySmall);Text(title,fontWeight=FontWeight.Bold,modifier=Modifier.padding(top=12.dp));Text(body,color=MpMuted)}}}
@Composable private fun ProgressList(items:List<ReadingProgress>,open:(Work,Chapter)->Unit,empty:String){if(items.isEmpty()){LibraryEmpty(empty,"As leituras realizadas aparecerão aqui.");return};LazyColumn(verticalArrangement=Arrangement.spacedBy(10.dp),contentPadding=PaddingValues(bottom=24.dp)){items(items,key={it.workId+it.chapterId}){item->ProgressRow(item){open(item.toWork(),item.toChapter())}}}}
@Composable private fun ProgressRow(item:ReadingProgress,open:()->Unit){Surface(Modifier.fillMaxWidth().clickable{open()},color=MpSurface,shape=RoundedCornerShape(18.dp),border=androidx.compose.foundation.BorderStroke(1.dp,MpLine)){Row(Modifier.padding(12.dp),verticalAlignment=Alignment.CenterVertically){AsyncImage(item.workCover,item.workTitle,Modifier.size(64.dp).clip(RoundedCornerShape(12.dp)).background(MpSurface2),contentScale=ContentScale.Crop);Column(Modifier.weight(1f).padding(start=12.dp)){Text(item.workTitle,fontWeight=FontWeight.Bold,maxLines=1,overflow=TextOverflow.Ellipsis);Text("${item.chapterLabel} • página ${item.page}/${item.totalPages}",color=MpMuted,style=MaterialTheme.typography.bodySmall);LinearProgressIndicator(progress={item.percent/100f},Modifier.fillMaxWidth().padding(top=9.dp));Text("${item.percent}% lido",color=MpAccent2,style=MaterialTheme.typography.labelSmall,modifier=Modifier.padding(top=4.dp))}}}}
@Composable private fun DownloadedRow(item:OfflineChapter,open:()->Unit,delete:()->Unit){Surface(Modifier.fillMaxWidth(),color=MpSurface,shape=RoundedCornerShape(18.dp),border=androidx.compose.foundation.BorderStroke(1.dp,MpLine)){Row(Modifier.fillMaxWidth().padding(12.dp),verticalAlignment=Alignment.CenterVertically){AsyncImage(item.workCover,item.workTitle,Modifier.size(58.dp).clip(RoundedCornerShape(12.dp)).background(MpSurface2),contentScale=ContentScale.Crop);Column(Modifier.weight(1f).padding(horizontal=12.dp).clickable{open()}){Text(item.workTitle,fontWeight=FontWeight.Bold,maxLines=1,overflow=TextOverflow.Ellipsis);Text("${item.chapterLabel} • ${item.pageCount} páginas",color=MpMuted,style=MaterialTheme.typography.bodySmall);Text("Disponível offline",color=MpAccent2,style=MaterialTheme.typography.labelSmall)};TextButton(delete){Text("Excluir")}}}}
@Composable private fun DownloadedWorkRow(work:Work,chapterCount:Int,open:()->Unit){Surface(Modifier.fillMaxWidth().clickable{open()},color=MpSurface,shape=RoundedCornerShape(18.dp),border=androidx.compose.foundation.BorderStroke(1.dp,MpLine)){Row(Modifier.fillMaxWidth().padding(12.dp),verticalAlignment=Alignment.CenterVertically){AsyncImage(work.cover,work.title,Modifier.width(72.dp).aspectRatio(3f/4f).clip(RoundedCornerShape(12.dp)).background(MpSurface2),contentScale=ContentScale.Crop);Column(Modifier.weight(1f).padding(horizontal=12.dp)){Text(work.title,fontWeight=FontWeight.Black,maxLines=2,overflow=TextOverflow.Ellipsis);Text("$chapterCount ${if(chapterCount==1)"capítulo baixado" else "capítulos baixados"}",color=MpAccent2,style=MaterialTheme.typography.bodySmall,modifier=Modifier.padding(top=4.dp));Text("Toque para abrir a página da obra",color=MpMuted,style=MaterialTheme.typography.labelSmall,modifier=Modifier.padding(top=4.dp))};Text("›",color=MpMuted,style=MaterialTheme.typography.headlineSmall)}}}
private fun OfflineChapter.toWork()=Work(workId,workTitle,"",workCover,"","","","",emptyList(),0,0)
private fun OfflineChapter.toChapter()=Chapter(chapterId,chapterLabel.substringAfter("Capítulo ").toDoubleOrNull(),"",true,0)
private fun ReadingProgress.toWork()=Work(workId,workTitle,"",workCover,"","","","",emptyList(),0,0)
private fun ReadingProgress.toChapter()=Chapter(chapterId,chapterLabel.substringAfter("Capítulo ").toDoubleOrNull(),"",true,0)
@Composable private fun Header(){Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(48.dp).clip(RoundedCornerShape(16.dp)).background(Brush.linearGradient(listOf(MpAccent,MpAccent2))),contentAlignment=Alignment.Center){Text("MP",fontWeight=FontWeight.Black)};Spacer(Modifier.width(12.dp));Column{Text("MP SCAN",fontWeight=FontWeight.Black,style=MaterialTheme.typography.titleMedium);Text("Sua próxima leitura começa aqui",color=MpMuted,style=MaterialTheme.typography.bodySmall)};Spacer(Modifier.weight(1f));Surface(shape=RoundedCornerShape(14.dp),color=MpSurface,border=androidx.compose.foundation.BorderStroke(1.dp,MpLine)){Box(Modifier.size(42.dp),contentAlignment=Alignment.Center){Text("♢")}}}}
@Composable private fun Home(works:List<Work>,modifier:Modifier,open:(Work)->Unit,continueReading:(Work,Chapter)->Unit){val context=LocalContext.current;val recent=ReadingStore(context.applicationContext).history().filter{it.percent<100}.distinctBy{it.workId}.take(10);var updates by remember(works){mutableStateOf<List<RecentUpdate>>(emptyList())};LaunchedEffect(works){updates=runCatching{CatalogRepository().recentUpdates(works)}.getOrDefault(emptyList())};LazyColumn(modifier.fillMaxSize().padding(horizontal=16.dp),contentPadding=PaddingValues(top=16.dp,bottom=32.dp),verticalArrangement=Arrangement.spacedBy(28.dp)){item{Header()};item{Hero(works.first(),open)};item{Rail("Em alta",works.sortedByDescending{it.reads}.take(10),true,open)};if(recent.isNotEmpty())item{Column{Text("Continuar lendo",fontWeight=FontWeight.Black,style=MaterialTheme.typography.headlineSmall);Spacer(Modifier.height(12.dp));LazyRow(horizontalArrangement=Arrangement.spacedBy(12.dp)){items(recent,key={it.workId}){item->Box(Modifier.width(260.dp)){ProgressRow(item){continueReading(item.toWork(),item.toChapter())}}}}}};item{RecentUpdates(updates,open)}}}
@Composable private fun Hero(w:Work,open:(Work)->Unit){Box(Modifier.fillMaxWidth().height(490.dp).clip(RoundedCornerShape(34.dp)).background(MpSurface)){AsyncImage(w.banner.ifBlank{w.cover},w.title,Modifier.fillMaxSize(),contentScale=ContentScale.Crop);Box(Modifier.fillMaxSize().background(Brush.horizontalGradient(listOf(Color(0xF207070A),Color(0xA607070A),Color.Transparent))));Box(Modifier.fillMaxSize().background(Brush.verticalGradient(listOf(Color.Transparent,Color(0xF507070A)))));Column(Modifier.align(Alignment.BottomStart).padding(26.dp).fillMaxWidth(.92f)){Text("DESTAQUE MP SCAN",color=MpAccent2,fontWeight=FontWeight.Black,style=MaterialTheme.typography.labelSmall);Spacer(Modifier.height(10.dp));Text(w.title,fontWeight=FontWeight.Black,style=MaterialTheme.typography.headlineLarge,maxLines=2,overflow=TextOverflow.Ellipsis);Text(w.synopsis,color=MpMuted,maxLines=3,overflow=TextOverflow.Ellipsis,modifier=Modifier.padding(vertical=12.dp));Button(onClick={open(w)},shape=RoundedCornerShape(14.dp)){Text("Ver detalhes",fontWeight=FontWeight.Black)}}}}
@Composable private fun Rail(title:String,works:List<Work>,ranked:Boolean,open:(Work)->Unit){Column{Text(title,fontWeight=FontWeight.Black,style=MaterialTheme.typography.headlineSmall);Spacer(Modifier.height(12.dp));LazyRow(horizontalArrangement=Arrangement.spacedBy(13.dp)){items(works,key={it.id}){w->Box{Card(w,open);if(ranked)Text((works.indexOf(w)+1).toString(),fontWeight=FontWeight.Black,style=MaterialTheme.typography.displaySmall,color=Color.White,modifier=Modifier.align(Alignment.BottomStart).background(Color(0xB30B0B0D)).padding(horizontal=8.dp))}}}}}
@Composable private fun RecentUpdates(updates:List<RecentUpdate>,open:(Work)->Unit){Column{Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text("Atualizações recentes",fontWeight=FontWeight.Black,style=MaterialTheme.typography.headlineSmall);Text("Capítulos que acabaram de chegar",color=MpMuted,style=MaterialTheme.typography.bodySmall)};Text("NOVO",color=MpAccent2,fontWeight=FontWeight.Black,style=MaterialTheme.typography.labelSmall)};Spacer(Modifier.height(14.dp));if(updates.isEmpty()){Text("As próximas atualizações aparecerão aqui.",color=MpMuted)}else updates.chunked(2).forEach{pair->Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(12.dp)){pair.forEach{update->val w=update.work;Surface(Modifier.weight(1f),color=MpSurface,shape=RoundedCornerShape(20.dp),border=androidx.compose.foundation.BorderStroke(1.dp,MpLine)){Column{Box(Modifier.fillMaxWidth().aspectRatio(3f/4f).clickable{open(w)}){AsyncImage(w.cover,w.title,Modifier.fillMaxSize(),contentScale=ContentScale.Crop);Text("NOVO",color=Color.White,fontWeight=FontWeight.Black,style=MaterialTheme.typography.labelSmall,modifier=Modifier.align(Alignment.TopStart).padding(9.dp).background(MpAccent,RoundedCornerShape(9.dp)).padding(horizontal=8.dp,vertical=4.dp))};Column(Modifier.padding(12.dp)){Text(w.title,fontWeight=FontWeight.Black,maxLines=2,overflow=TextOverflow.Ellipsis);Text(update.chapter.label,color=MpAccent2,fontWeight=FontWeight.Bold,style=MaterialTheme.typography.bodySmall,modifier=Modifier.padding(top=6.dp));if(update.chapter.title.isNotBlank())Text(update.chapter.title,color=MpMuted,style=MaterialTheme.typography.bodySmall,maxLines=1,overflow=TextOverflow.Ellipsis);Text(formatUpdateDate(update.updatedAt),color=MpMuted,style=MaterialTheme.typography.labelSmall,modifier=Modifier.padding(top=3.dp));Button(onClick={open(w)},modifier=Modifier.fillMaxWidth().padding(top=10.dp),shape=RoundedCornerShape(12.dp),contentPadding=PaddingValues(vertical=8.dp)){Text("LER AGORA",fontWeight=FontWeight.Black,style=MaterialTheme.typography.labelMedium)}}}}};if(pair.size==1)Spacer(Modifier.weight(1f))};Spacer(Modifier.height(12.dp))}}}
private fun formatUpdateDate(value:Long):String{if(value<=0)return "Atualização recente";val millis=if(value<100000000000L)value*1000 else value;return SimpleDateFormat("dd/MM/yyyy",Locale("pt","BR")).format(Date(millis))}
@Composable private fun Card(w:Work,open:(Work)->Unit){Column(Modifier.width(148.dp).clickable{open(w)}){AsyncImage(w.cover,w.title,Modifier.fillMaxWidth().aspectRatio(3f/4f).clip(RoundedCornerShape(18.dp)).background(MpSurface2),contentScale=ContentScale.Crop);Text(w.title,fontWeight=FontWeight.Bold,maxLines=1,overflow=TextOverflow.Ellipsis,modifier=Modifier.padding(top=8.dp));Text(w.type,color=MpMuted,style=MaterialTheme.typography.bodySmall)}}
@Composable private fun Search(works:List<Work>,open:(Work)->Unit){
 var query by remember{mutableStateOf("")};var status by remember{mutableStateOf("")};var genre by remember{mutableStateOf("")}
 val genres=remember(works){works.flatMap{it.genres}.distinct().sorted()}
 val filtered=remember(works,query,status,genre){works.filter{w->(query.isBlank()||(w.title+" "+w.author+" "+w.genres.joinToString()).contains(query,true))&&(status.isBlank()||localizedStatus(w.status).equals(status,true))&&(genre.isBlank()||w.genres.any{it.equals(genre,true)})}}
 Column(Modifier.fillMaxSize().padding(horizontal=16.dp,vertical=14.dp)){Header();Spacer(Modifier.height(18.dp));OutlinedTextField(query,{query=it},Modifier.fillMaxWidth(),singleLine=true,shape=RoundedCornerShape(16.dp),leadingIcon={Text("⌕")},label={Text("Nome, gênero ou autor")});LazyRow(Modifier.padding(vertical=12.dp),horizontalArrangement=Arrangement.spacedBy(8.dp)){item{FilterChip(status.isBlank(),{status=""},{Text("Todos")})};items(listOf("Em andamento","Completa","Em pausa","Futura","Cancelada")){s->FilterChip(status==s,{status=if(status==s)"" else s},{Text(s)})}};if(genres.isNotEmpty())LazyRow(horizontalArrangement=Arrangement.spacedBy(8.dp)){items(genres){g->FilterChip(genre==g,{genre=if(genre==g)"" else g},{Text(g)})}};Text("${filtered.size} obras",color=MpMuted,modifier=Modifier.padding(vertical=10.dp));LazyVerticalGrid(GridCells.Adaptive(140.dp),horizontalArrangement=Arrangement.spacedBy(12.dp),verticalArrangement=Arrangement.spacedBy(18.dp)){gridItems(filtered,key={it.id}){Card(it,open)}}}
}
@Composable private fun WorkDetails(work:Work,newBadge:NewBadgeStyle,back:()->Unit){
 val context=LocalContext.current;val appContext=context.applicationContext;val favorites=remember{FavoritesStore(appContext)};val libraryRepository=remember{LibraryRepository()};val readingStore=remember{ReadingStore(appContext)};val offlineStore=remember{OfflineStore(appContext)};val repository=remember{CatalogRepository()};val social=remember{WorkSocialRepository()};val accountStore=remember{AccountStore(appContext)};var session by remember{mutableStateOf(accountStore.session())};val accountRepository=remember{AccountRepository()};val scope=rememberCoroutineScope()
 var favorite by remember(work.id){mutableStateOf(favorites.contains(work.id))};var chapters by remember(work.id){mutableStateOf<List<Chapter>>(emptyList())};var loading by remember(work.id){mutableStateOf(true)};var reading by remember(work.id){mutableStateOf<Chapter?>(null)}
 var tab by remember(work.id){mutableStateOf("Capítulos")};var rating by remember(work.id){mutableStateOf(WorkRating())};var reactions by remember(work.id){mutableStateOf<List<WorkReaction>>(emptyList())};var socialError by remember{mutableStateOf("")}
 var downloadingAll by remember(work.id){mutableStateOf(false)};var bulkProgress by remember(work.id){mutableIntStateOf(0)};var bulkMessage by remember(work.id){mutableStateOf("")};var bulkError by remember(work.id){mutableStateOf("")}
 var downloadedIds by remember(work.id){mutableStateOf(offlineStore.downloads().filter{it.workId==work.id}.map{it.chapterId}.toSet())}
 var subscribed by remember(work.id){mutableStateOf(false)};var collectionDialog by remember(work.id){mutableStateOf(false)};var actionMessage by remember{mutableStateOf("")}
 val notificationPermission=rememberLauncherForActivityResult(ActivityResultContracts.RequestPermission()){granted->actionMessage=if(granted)"Notificações de capítulos ativadas." else "Permita notificações nos ajustes do celular para receber os avisos."}
 val chapterProgress=remember(work.id){mutableStateMapOf<String,Int>()}
 val chapterErrors=remember(work.id){mutableStateMapOf<String,Boolean>()}
 if(reading!=null){BackHandler{reading=null};Reader(work,reading!!){reading=null};return}
 LaunchedEffect(work.id){session?.let{old->runCatching{accountRepository.refresh(old)}.onSuccess{fresh->session=fresh;accountStore.save(fresh)}};subscribed=session?.let{runCatching{libraryRepository.notificationEnabled(it,work.id)}.getOrDefault(false)}?:false;val savedDownloads=offlineStore.downloads().filter{it.workId==work.id};downloadedIds=savedDownloads.map{it.chapterId}.toSet();val saved=savedDownloads.map{it.toChapter()};runCatching{repository.chapters(work.id)}.onSuccess{remote->chapters=(remote+saved).distinctBy{it.id}.sortedByDescending{it.number?:-1.0}}.onFailure{chapters=saved};rating=runCatching{social.rating(work.id,session)}.getOrDefault(WorkRating());reactions=runCatching{social.reactions(work.id,session)}.getOrDefault(emptyList());loading=false}
 LaunchedEffect(work.id,chapters){while(true){val infos=withContext(Dispatchers.IO){WorkManager.getInstance(appContext).getWorkInfosByTag("work-download-${work.id}").get()};val byChapter=infos.mapNotNull{info->info.tags.firstOrNull{tag->tag.startsWith("chapter-download-${work.id}-")}?.removePrefix("chapter-download-${work.id}-")?.let{it to info}}.toMap();chapters.forEach{chapter->val info=byChapter[chapter.id];when{info==null->chapterProgress.remove(chapter.id);!info.state.isFinished->{chapterProgress[chapter.id]=info.progress.getInt(ChapterDownloadWorker.PROGRESS,0);chapterErrors.remove(chapter.id)};info.state==androidx.work.WorkInfo.State.FAILED->{chapterProgress.remove(chapter.id);chapterErrors[chapter.id]=true;bulkError=info.outputData.getString(ChapterDownloadWorker.ERROR)?:"Não foi possível baixar um dos capítulos."};else->chapterProgress.remove(chapter.id)}};downloadedIds=offlineStore.downloads().filter{it.workId==work.id}.map{it.chapterId}.toSet();downloadingAll=byChapter.values.any{!it.state.isFinished};if(chapters.isNotEmpty())bulkProgress=(downloadedIds.size.coerceAtMost(chapters.size)*100)/chapters.size;if(!downloadingAll&&downloadedIds.isNotEmpty()&&bulkError.isBlank())bulkMessage=if(downloadedIds.size==chapters.size)"Todos os capítulos foram baixados." else "${downloadedIds.size} de ${chapters.size} capítulos baixados.";delay(700)}}
 val progress=remember(work.id,chapters){readingStore.history().filter{it.workId==work.id}.associateBy{it.chapterId}}
 val continueChapter=chapters.firstOrNull{(progress[it.id]?.percent?:0)<100}?:chapters.firstOrNull()
 val allDownloaded=chapters.isNotEmpty()&&chapters.all{it.id in downloadedIds}
 fun downloadChapter(chapter:Chapter){if(chapter.id in downloadedIds||chapterProgress.containsKey(chapter.id))return;chapterErrors.remove(chapter.id);chapterProgress[chapter.id]=0;ChapterDownloadWorker.enqueue(appContext,work,chapter)}
 if(collectionDialog)CollectionPickerDialog(libraryRepository,session,work.id,{collectionDialog=false}){message->actionMessage=message}
 LazyColumn(Modifier.fillMaxSize(),contentPadding=PaddingValues(bottom=30.dp)){
  item{WorkHero(work,chapters.size,rating.average,back)}
  item{Column(Modifier.padding(horizontal=12.dp,vertical=14.dp)){Button({continueChapter?.let{reading=it}},Modifier.fillMaxWidth().height(58.dp),enabled=continueChapter!=null,shape=RoundedCornerShape(17.dp)){Text(if(progress.isNotEmpty())"▶ Continuar lendo" else "▶ Começar a ler",fontWeight=FontWeight.Black)};Row(Modifier.padding(top=10.dp),horizontalArrangement=Arrangement.spacedBy(10.dp)){OutlinedButton({favorite=favorites.toggle(work.id)}){Text(if(favorite)"♥" else "♡")};OutlinedButton({val current=session;if(current==null)actionMessage="Entre na conta para ativar notificações." else scope.launch{runCatching{val fresh=accountRepository.refresh(current);session=fresh;accountStore.save(fresh);val enabled=!subscribed;libraryRepository.setNotification(fresh,work.id,enabled);enabled}.onSuccess{enabled->subscribed=enabled;if(enabled){online.mpscan.app.data.NewChapterWorker.runNow(appContext);if(android.os.Build.VERSION.SDK_INT>=33&&ContextCompat.checkSelfPermission(context,Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)notificationPermission.launch(Manifest.permission.POST_NOTIFICATIONS)else actionMessage="Você receberá avisos quando sair capítulo novo."}else actionMessage="Avisos de novos capítulos desativados."}.onFailure{actionMessage=it.message?:"Não foi possível atualizar as notificações."}}}){Text(if(subscribed)"🔔" else "♢")};OutlinedButton({if(session==null)actionMessage="Entre na conta para usar suas coleções." else collectionDialog=true}){Text("＋")}};if(actionMessage.isNotBlank())Text(actionMessage,color=MpAccent2,style=MaterialTheme.typography.bodySmall,modifier=Modifier.padding(top=9.dp))}}
  if(reactions.isNotEmpty())item{WorkReactions(reactions){chosen->val current=session;if(current==null){socialError="Entre na conta para escolher uma reação."}else scope.launch{runCatching{if(current.refreshToken.isBlank())current else accountRepository.refresh(current)}.mapCatching{fresh->session=fresh;accountStore.save(fresh);social.react(work.id,chosen,fresh);fresh}.onSuccess{fresh->reactions=social.reactions(work.id,fresh);socialError="Reação registrada com sucesso."}.onFailure{socialError=it.message?:"Não foi possível salvar sua reação."}}}}
  item{RatingPanel(rating,session!=null){note->val current=session;if(current==null)socialError="Entre na conta para avaliar." else scope.launch{runCatching{if(current.refreshToken.isBlank())current else accountRepository.refresh(current)}.mapCatching{fresh->session=fresh;accountStore.save(fresh);social.rate(work.id,note,fresh);fresh}.onSuccess{fresh->rating=social.rating(work.id,fresh);socialError="Avaliação salva com sucesso."}.onFailure{socialError=it.message?:"Não foi possível salvar a avaliação."}}}}
  if(socialError.isNotBlank())item{Text(socialError,color=MaterialTheme.colorScheme.error,modifier=Modifier.padding(horizontal=16.dp,vertical=8.dp))}
  item{WorkTabs(tab,chapters.size){tab=it}}
  when(tab){
   "Sobre"->{item{SynopsisCard(work)};item{WorkInformation(work,chapters.firstOrNull()?.updatedAt?:work.updatedAt)}}
   "Comentários"->item{CommentsSection("obra",work.id,"",Modifier.padding(horizontal=12.dp,vertical=18.dp))}
   else->{
    item{DownloadAllCard(allDownloaded,downloadingAll,bulkProgress,bulkMessage,bulkError,!loading&&chapters.isNotEmpty()){if(chapters.isNotEmpty()&&!allDownloaded){bulkError="";bulkMessage="O download continuará mesmo se você sair do aplicativo.";chapters.filter{it.id !in downloadedIds}.forEach{downloadChapter(it)};downloadingAll=true}}}
    if(loading)item{LinearProgressIndicator(Modifier.fillMaxWidth().padding(horizontal=16.dp))}
    items(chapters,key={it.id}){c->ChapterRow(c,progress[c.id],c.id in downloadedIds,chapterProgress[c.id],chapterErrors[c.id]==true,{reading=c}){downloadChapter(c)}}
   }
  }
 }
}
@Composable private fun CollectionPickerDialog(repository:LibraryRepository,session:online.mpscan.app.data.AccountSession?,workId:String,close:()->Unit,message:(String)->Unit){
 val scope=rememberCoroutineScope();var collections by remember{mutableStateOf<List<UserCollection>>(emptyList())};var selected by remember{mutableStateOf<Set<String>>(emptySet())};var loading by remember{mutableStateOf(true)};var saving by remember{mutableStateOf(false)};var error by remember{mutableStateOf("")};var creating by remember{mutableStateOf(false)};var input by remember{mutableStateOf("")};var publicCollection by remember{mutableStateOf(false)}
 LaunchedEffect(session?.uid){if(session==null){error="Entre na conta para usar suas coleções.";loading=false}else runCatching{repository.collections(session)}.onSuccess{list->collections=list;selected=list.filter{workId in it.workIds}.map{it.id}.toSet()}.onFailure{error=it.message?:"Não foi possível carregar suas coleções."}.also{loading=false}}
 AlertDialog(onDismissRequest=close,title={Text("Adicionar à coleção")},text={Column{Text("Escolha suas coleções públicas ou privadas.",color=MpMuted);Spacer(Modifier.height(12.dp));when{loading->CircularProgressIndicator();error.isNotBlank()->Text(error,color=MaterialTheme.colorScheme.error);collections.isEmpty()&&!creating->Text("Você ainda não criou uma coleção.",color=MpMuted);else->LazyColumn(Modifier.heightIn(max=320.dp)){items(collections,key={it.id}){item->val checked=item.id in selected;Surface(Modifier.fillMaxWidth().padding(vertical=4.dp).clickable{selected=if(checked)selected-item.id else selected+item.id},color=if(checked)MpAccent.copy(.16f)else MpSurface2,shape=RoundedCornerShape(14.dp),border=androidx.compose.foundation.BorderStroke(1.dp,if(checked)MpAccent else MpLine)){Row(Modifier.padding(13.dp),verticalAlignment=Alignment.CenterVertically){Text(if(checked)"✓" else "▣",color=MpAccent);Column(Modifier.weight(1f).padding(horizontal=10.dp)){Text(item.name,fontWeight=FontWeight.Bold);Text(if(item.isPublic)"🌐 Pública" else "🔒 Privada",color=MpMuted,style=MaterialTheme.typography.labelSmall)};Text(if(checked)"Selecionada" else "Adicionar",color=MpMuted,style=MaterialTheme.typography.labelSmall)}}}}};if(creating){Spacer(Modifier.height(10.dp));OutlinedTextField(input,{input=it},Modifier.fillMaxWidth(),singleLine=true,label={Text("Nome da coleção")});Row(verticalAlignment=Alignment.CenterVertically){Checkbox(publicCollection,{publicCollection=it});Text(if(publicCollection)"Coleção pública" else "Coleção privada")};Button({val current=session;if(current!=null&&input.isNotBlank())scope.launch{saving=true;runCatching{repository.createCollection(current,input,publicCollection)}.onSuccess{created->collections=(collections+created).sortedBy{it.name.lowercase()};input="";creating=false;message("Coleção criada.")}.onFailure{error=it.message?:"Não foi possível criar a coleção."};saving=false}},enabled=!saving){Text("Criar")}}else TextButton({creating=true}){Text("＋ Nova coleção")}}},confirmButton={Button({val current=session;if(current!=null)scope.launch{saving=true;error="";runCatching{collections.forEach{item->val wanted=item.id in selected;val has=workId in item.workIds;if(wanted!=has)repository.setWork(current,item,workId,wanted)}}.onSuccess{message("Coleções atualizadas.");close()}.onFailure{error=it.message?:"Não foi possível atualizar as coleções."};saving=false}},enabled=!loading&&!saving&&session!=null){Text(if(saving)"Salvando…" else "Salvar alterações")}},dismissButton={TextButton(close){Text("Cancelar")}})
}
@Composable private fun WorkHero(work:Work,chapterCount:Int,average:Double,back:()->Unit){Box(Modifier.fillMaxWidth().height(520.dp)){AsyncImage(work.banner.ifBlank{work.cover},work.title,Modifier.fillMaxSize(),contentScale=ContentScale.Crop);Box(Modifier.fillMaxSize().background(Brush.verticalGradient(listOf(Color(0x22000000),Color(0xAA08080B),MpBackground))));FilledTonalButton(back,Modifier.padding(18.dp)){Text("←")};Surface(Modifier.align(Alignment.TopEnd).padding(18.dp),shape=RoundedCornerShape(18.dp),color=Color(0x990B0B0D)){Text("↗",Modifier.padding(14.dp),fontWeight=FontWeight.Black)};Row(Modifier.align(Alignment.BottomStart).padding(18.dp),verticalAlignment=Alignment.Bottom){AsyncImage(work.cover,work.title,Modifier.width(140.dp).aspectRatio(3f/4f).clip(RoundedCornerShape(20.dp)),contentScale=ContentScale.Crop);Column(Modifier.weight(1f).padding(start=16.dp,bottom=4.dp)){Text("MP SCAN • OBRA",color=MpMuted,fontWeight=FontWeight.Black,style=MaterialTheme.typography.labelSmall);Text(work.title,fontWeight=FontWeight.Black,style=MaterialTheme.typography.headlineMedium,maxLines=3,overflow=TextOverflow.Ellipsis);if(work.alternateTitle.isNotBlank())Text(work.alternateTitle,color=MpMuted,maxLines=2,modifier=Modifier.padding(top=5.dp));LazyRow(Modifier.padding(top=12.dp),horizontalArrangement=Arrangement.spacedBy(7.dp)){item{WorkPill("★ ${"%.1f".format(Locale.US,average)}")};item{WorkPill(localizedStatus(work.status))};item{WorkPill("$chapterCount capítulos")}}}}}}
@Composable private fun WorkPill(text:String){Surface(color=MpSurface.copy(.9f),shape=RoundedCornerShape(18.dp),border=androidx.compose.foundation.BorderStroke(1.dp,MpLine)){Text(text,Modifier.padding(horizontal=12.dp,vertical=7.dp),style=MaterialTheme.typography.bodySmall)}}
@Composable private fun WorkReactions(items:List<WorkReaction>,choose:(WorkReaction)->Unit){Surface(Modifier.fillMaxWidth().padding(horizontal=12.dp,vertical=8.dp),color=MpSurface,shape=RoundedCornerShape(24.dp),border=androidx.compose.foundation.BorderStroke(1.dp,Color(0xff57253d))){Column(Modifier.padding(18.dp)){Text("✨ Qual foi sua reação?",fontWeight=FontWeight.Black,style=MaterialTheme.typography.titleLarge);Text("Escolha uma reação criada pela equipe para esta obra.",color=MpMuted,modifier=Modifier.padding(top=4.dp,bottom=14.dp));LazyRow(horizontalArrangement=Arrangement.spacedBy(10.dp)){items(items,key={it.source+it.id}){reaction->Surface(Modifier.width(132.dp).clickable{choose(reaction)},color=if(reaction.selected)Color(0xff2b1622)else MpSurface2,shape=RoundedCornerShape(20.dp),border=androidx.compose.foundation.BorderStroke(if(reaction.selected)2.dp else 1.dp,if(reaction.selected)MpAccent2 else MpLine)){Column(Modifier.padding(12.dp),horizontalAlignment=Alignment.CenterHorizontally){if(reaction.image.isNotBlank())AsyncImage(reaction.image,reaction.label,Modifier.size(66.dp),contentScale=ContentScale.Fit);Text(reaction.label,fontWeight=FontWeight.Bold,maxLines=2,overflow=TextOverflow.Ellipsis,modifier=Modifier.padding(top=8.dp));if(reaction.source=="global")Text("PARA TODOS",color=MpAccent2,style=MaterialTheme.typography.labelSmall,modifier=Modifier.padding(top=8.dp));Text(if(reaction.selected)"Sua reação • ${reaction.votes} votos" else "${reaction.votes} votos",color=MpMuted,style=MaterialTheme.typography.labelSmall,modifier=Modifier.padding(top=7.dp))}}}}}}}
@Composable private fun RatingPanel(rating:WorkRating,logged:Boolean,rate:(Int)->Unit){Surface(Modifier.fillMaxWidth().padding(horizontal=12.dp,vertical=8.dp),color=Color(0xff18171d),shape=RoundedCornerShape(24.dp),border=androidx.compose.foundation.BorderStroke(1.dp,Color(0xff715a2a))){Column(Modifier.padding(20.dp)){Text("AVALIAÇÃO DOS LEITORES",color=Color(0xffff6e9c),fontWeight=FontWeight.Black,style=MaterialTheme.typography.labelMedium);Row(verticalAlignment=Alignment.Bottom){Text("${"%.1f".format(Locale.US,rating.average)}",fontWeight=FontWeight.Black,style=MaterialTheme.typography.displayMedium);Text("★",color=Color(0xffffc13d),style=MaterialTheme.typography.headlineMedium,modifier=Modifier.padding(bottom=8.dp))};Text("${rating.total} ${if(rating.total==1)"avaliação" else "avaliações"} no total",color=MpMuted);Spacer(Modifier.height(14.dp));for(note in 5 downTo 1){val count=rating.counts[note]?:0;val part=if(rating.total==0)0f else count.toFloat()/rating.total;Row(Modifier.fillMaxWidth().padding(vertical=4.dp),verticalAlignment=Alignment.CenterVertically){Text("$note★",Modifier.width(42.dp));LinearProgressIndicator(progress={part},Modifier.weight(1f),color=Color(0xffffc13d),trackColor=MpSurface2);Text("$count",Modifier.width(32.dp),textAlign=androidx.compose.ui.text.style.TextAlign.End,color=MpMuted)}};HorizontalDivider(Modifier.padding(vertical=16.dp),color=MpLine);Text("Avaliações dos leitores",fontWeight=FontWeight.Bold,style=MaterialTheme.typography.titleMedium);Text(if(logged)"Toque em uma estrela para avaliar. Você pode mudar quando quiser." else "Entre na conta para participar da avaliação.",color=MpMuted,style=MaterialTheme.typography.bodySmall);Row(Modifier.padding(top=12.dp),horizontalArrangement=Arrangement.spacedBy(9.dp)){for(note in 1..5){OutlinedButton({rate(note)},enabled=logged,contentPadding=PaddingValues(0.dp),modifier=Modifier.size(52.dp),border=androidx.compose.foundation.BorderStroke(1.dp,if(note<=rating.mine)Color(0xffffc13d)else MpLine)){Text("★",color=if(note<=rating.mine)Color(0xffffc13d)else MpMuted)}}}}}}
@Composable private fun WorkTabs(selected:String,count:Int,change:(String)->Unit){Row(Modifier.fillMaxWidth().padding(horizontal=12.dp,vertical=12.dp).clip(RoundedCornerShape(20.dp)).background(MpSurface2).padding(5.dp),horizontalArrangement=Arrangement.spacedBy(5.dp)){listOf("Sobre","Capítulos","Comentários").forEach{name->Surface(Modifier.weight(1f).clickable{change(name)},color=if(selected==name)Color(0xff2b1822)else Color.Transparent,shape=RoundedCornerShape(15.dp)){Column(Modifier.padding(vertical=12.dp),horizontalAlignment=Alignment.CenterHorizontally){Text(if(name=="Capítulos")"Capítulos $count" else name,fontWeight=FontWeight.Bold,color=if(selected==name)Color.White else MpMuted);if(selected==name)Box(Modifier.padding(top=7.dp).width(58.dp).height(3.dp).background(MpAccent2,RoundedCornerShape(2.dp)))}}}}}
@Composable private fun SynopsisCard(work:Work){Surface(Modifier.fillMaxWidth().padding(horizontal=12.dp,vertical=8.dp),color=MpSurface,shape=RoundedCornerShape(24.dp),border=androidx.compose.foundation.BorderStroke(1.dp,MpLine)){Column(Modifier.padding(20.dp)){Text("SINOPSE",color=MpAccent2,fontWeight=FontWeight.Black,style=MaterialTheme.typography.labelMedium);Text(work.synopsis.ifBlank{"Sinopse ainda não informada."},modifier=Modifier.padding(top=14.dp),lineHeight=28.sp);if(work.genres.isNotEmpty())LazyRow(Modifier.padding(top=18.dp),horizontalArrangement=Arrangement.spacedBy(8.dp)){items(work.genres){genre->Surface(color=Color(0xff2a1720),shape=RoundedCornerShape(18.dp),border=androidx.compose.foundation.BorderStroke(1.dp,Color(0xff5b2b42))){Text(genre,Modifier.padding(horizontal=14.dp,vertical=8.dp),fontWeight=FontWeight.Bold)}}}}}}
@Composable
private fun WorkInformation(work: Work, lastUpdate: Long) {
    val rows = listOf(
        "TIPO" to localizedType(work.type),
        "STATUS" to localizedStatus(work.status),
        "AGENDA" to work.schedule,
        "ÚLTIMA ATUALIZAÇÃO" to formatWorkDate(lastUpdate),
        "AUTOR" to work.author,
        "ARTISTA" to work.artist,
        "SCAN" to work.scan,
        "IDIOMA" to work.language
    ).filter { it.second.isNotBlank() }
    Column(Modifier.padding(horizontal = 12.dp, vertical = 4.dp)) {
        rows.forEach { (label, value) ->
            Surface(
                Modifier.fillMaxWidth().padding(vertical = 6.dp),
                color = MpSurface,
                shape = RoundedCornerShape(20.dp),
