plugins { id 'com.android.application' }

android {
    namespace 'online.mpscan.app'
    compileSdk 35

    defaultConfig {
        applicationId 'online.mpscan.app'
        minSdk 24
        targetSdk 35
        versionCode 6
        versionName '1.4.1'
    }
}

dependencies {
    implementation 'androidx.activity:activity:1.10.1'
}
