package online.mpscan.app.ui
import androidx.compose.foundation.*
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.*
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.*
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.PasswordVisualTransformation
import androidx.compose.ui.unit.dp
import coil3.compose.AsyncImage
import kotlinx.coroutines.launch
import online.mpscan.app.data.*
import online.mpscan.app.ui.theme.*
@Composable fun AccountProfileScreen(openSettings:()->Unit){val ctx=LocalContext.current;val store=remember{AccountStore(ctx)};val repo=remember{AccountRepository()};val scope=rememberCoroutineScope();var session by remember{mutableStateOf(store.session())};var profile by remember{mutableStateOf<AccountProfile?>(null)};var busy by remember{mutableStateOf(session!=null)};var error by remember{mutableStateOf("")};var login by remember{mutableStateOf(false)};var edit by remember{mutableStateOf(false)}
 fun load(){val s=session?:return;scope.launch{busy=true;runCatching{repo.profile(s)}.onSuccess{profile=it;error=""}.onFailure{error=it.message?:"Não foi possível carregar o perfil."};busy=false}}
 LaunchedEffect(session?.uid){if(session!=null)load()};if(login)LoginDialog({login=false}){e,p->scope.launch{busy=true;runCatching{repo.signIn(e,p)}.onSuccess{session=it;store.save(it);login=false}.onFailure{error=it.message?:"Não foi possível entrar."};busy=false}};if(edit&&profile!=null)EditDialog(profile!!,{edit=false}){p->scope.launch{busy=true;runCatching{repo.saveProfile(session!!,p)}.onSuccess{profile=p;edit=false}.onFailure{error=it.message?:"Não foi possível salvar."};busy=false}}
 val p=profile;LazyColumn(Modifier.fillMaxSize(),contentPadding=PaddingValues(bottom=34.dp)){item{Box(Modifier.fillMaxWidth().height(245.dp).background(Brush.linearGradient(listOf(Color(0xFF36206D),MpAccent,Color(0xFFB13B80))))){if(!p?.cover.isNullOrBlank())AsyncImage(p!!.cover,null,Modifier.fillMaxSize(),contentScale=ContentScale.Crop);Box(Modifier.fillMaxSize().background(Brush.verticalGradient(listOf(Color.Transparent,MpBackground))));Text("MP SCAN",fontWeight=FontWeight.Black,style=MaterialTheme.typography.headlineSmall,modifier=Modifier.padding(18.dp));Box(Modifier.align(Alignment.BottomStart).padding(start=18.dp).size(98.dp).clip(RoundedCornerShape(30.dp)).background(MpSurface2),contentAlignment=Alignment.Center){if(!p?.photo.isNullOrBlank())AsyncImage(p!!.photo,null,Modifier.fillMaxSize(),contentScale=ContentScale.Crop)else Text(p?.name?.take(1)?.uppercase()?:"MP",fontWeight=FontWeight.Black,style=MaterialTheme.typography.headlineLarge,color=MpAccent)}}}
 item{Column(Modifier.padding(horizontal=18.dp)){if(session==null){Text("Seu perfil",fontWeight=FontWeight.Black,style=MaterialTheme.typography.headlineMedium);Text("Entre para carregar sua conta, foto, capa, nome, arroba e bio.",color=MpMuted,modifier=Modifier.padding(top=5.dp));Button({login=true},Modifier.fillMaxWidth().padding(top=18.dp)){Text("Entrar ou criar conta")}}else{Text(p?.name?:"Carregando perfil…",fontWeight=FontWeight.Black,style=MaterialTheme.typography.headlineMedium);if(!p?.username.isNullOrBlank())Text("@${p!!.username.removePrefix("@")}",color=MpAccent2);if(!p?.bio.isNullOrBlank())Text(p!!.bio,color=MpMuted,modifier=Modifier.padding(top=8.dp));Text(if(p?.isPublic==false)"🔒 Perfil privado" else "🌐 Perfil público",color=MpMuted,modifier=Modifier.padding(top=8.dp));Row(Modifier.fillMaxWidth().padding(top=18.dp),horizontalArrangement=Arrangement.spacedBy(8.dp)){Stat("${p?.followers?:0}","Seguidores",Modifier.weight(1f));Stat("${p?.following?:0}","Seguindo",Modifier.weight(1f));Stat("${p?.comments?:0}","Comentários",Modifier.weight(1f))};Button({edit=true},Modifier.fillMaxWidth().padding(top=16.dp)){Text("✎ Editar perfil")};OutlinedButton({store.clear();session=null;profile=null},Modifier.fillMaxWidth().padding(top=8.dp)){Text("Sair da conta")}};if(busy)LinearProgressIndicator(Modifier.fillMaxWidth().padding(top=12.dp));if(error.isNotBlank())Text(error,color=MaterialTheme.colorScheme.error,modifier=Modifier.padding(top=10.dp));Text("Conta e aplicativo",fontWeight=FontWeight.Black,style=MaterialTheme.typography.titleLarge,modifier=Modifier.padding(top=24.dp,bottom=8.dp));Menu("⚙","Configurações","Leitura, downloads, privacidade e aparência",openSettings)}}}}
@Composable private fun Stat(v:String,l:String,m:Modifier){Surface(m,color=MpSurface,shape=RoundedCornerShape(17.dp),border=BorderStroke(1.dp,MpLine)){Column(Modifier.padding(vertical=13.dp),horizontalAlignment=Alignment.CenterHorizontally){Text(v,fontWeight=FontWeight.Black,style=MaterialTheme.typography.titleLarge);Text(l,color=MpMuted,style=MaterialTheme.typography.labelSmall)}}}
@Composable private fun Menu(i:String,t:String,s:String,go:()->Unit){Surface(Modifier.fillMaxWidth().clickable{go()},color=MpSurface,shape=RoundedCornerShape(18.dp),border=BorderStroke(1.dp,MpLine)){Row(Modifier.padding(15.dp)){Text(i,color=MpAccent);Column(Modifier.weight(1f).padding(horizontal=12.dp)){Text(t,fontWeight=FontWeight.Bold);Text(s,color=MpMuted)}}}}
@Composable private fun LoginDialog(close:()->Unit,go:(String,String)->Unit){var e by remember{mutableStateOf("")};var p by remember{mutableStateOf("")};AlertDialog(onDismissRequest=close,title={Text("Entrar na MP SCAN")},text={Column{OutlinedTextField(e,{e=it},label={Text("E-mail")});OutlinedTextField(p,{p=it},label={Text("Senha")},visualTransformation=PasswordVisualTransformation())}},confirmButton={Button({go(e,p)},enabled=e.isNotBlank()&&p.isNotBlank()){Text("Entrar")}},dismissButton={TextButton(close){Text("Cancelar")}})}
@Composable private fun EditDialog(x:AccountProfile,close:()->Unit,save:(AccountProfile)->Unit){var n by remember{mutableStateOf(x.name)};var u by remember{mutableStateOf(x.username)};var b by remember{mutableStateOf(x.bio)};var ph by remember{mutableStateOf(x.photo)};var co by remember{mutableStateOf(x.cover)};var pub by remember{mutableStateOf(x.isPublic)};AlertDialog(onDismissRequest=close,title={Text("Editar perfil")},text={Column(Modifier.verticalScroll(rememberScrollState())){OutlinedTextField(n,{n=it.take(40)},label={Text("Nome")});OutlinedTextField(u,{u=it.filterNot(Char::isWhitespace).take(24)},label={Text("@ de usuário")});OutlinedTextField(b,{b=it.take(180)},label={Text("Bio")},minLines=3);OutlinedTextField(ph,{ph=it},label={Text("URL da foto")});OutlinedTextField(co,{co=it},label={Text("URL da capa")});Row(verticalAlignment=Alignment.CenterVertically){Switch(pub,{pub=it});Text(if(pub)"Perfil público" else "Perfil privado",modifier=Modifier.padding(start=8.dp))}}},confirmButton={Button({save(x.copy(name=n.trim(),username=u.removePrefix("@"),bio=b.trim(),photo=ph.trim(),cover=co.trim(),isPublic=pub))},enabled=n.isNotBlank()){Text("Salvar")}},dismissButton={TextButton(close){Text("Cancelar")}})}