package online.mpscan.app.ui
import androidx.compose.foundation.*
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.*
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.PasswordVisualTransformation
import androidx.compose.ui.unit.dp
import coil3.compose.AsyncImage
import kotlinx.coroutines.*
import online.mpscan.app.data.*
import online.mpscan.app.ui.theme.*
import org.json.JSONObject
import java.net.*
private data class CM(val id:String,val name:String,val username:String,val photo:String,val text:String,val spoiler:Boolean,val frame:CF)
private data class CF(val name:String="",val color:String="#8d2bff",val background:String="#17171d",val image:String="",val width:Int=2)
private class API{val b="https://nnnsss-23f2f-default-rtdb.firebaseio.com";fun e(v:String)=URLEncoder.encode(v,"UTF-8");fun path(t:String,w:String,c:String)=if(t=="obra")"comentariosV1/obra/${e(w)}" else "comentariosV1/capitulo/${e(w)}/${e(c)}";fun q(url:String,m:String="GET",body:String?=null):JSONObject{val x=URL(url).openConnection() as HttpURLConnection;x.requestMethod=m;x.connectTimeout=15000;x.readTimeout=25000;x.setRequestProperty("Content-Type","application/json");if(body!=null){x.doOutput=true;x.outputStream.use{it.write(body.toByteArray())}};val ok=x.responseCode in 200..299;val s=(if(ok)x.inputStream else x.errorStream)?.bufferedReader()?.use{it.readText()}.orEmpty();x.disconnect();if(!ok)error(if("TOKEN_EXPIRED" in s)"Sua sessão expirou. Entre novamente." else "Não foi possível conectar.");return if(s.isBlank()||s=="null")JSONObject()else JSONObject(s)}
 suspend fun list(t:String,w:String,c:String)=withContext(Dispatchers.IO){val x=q("$b/${path(t,w,c)}.json");val ids=runCatching{q("$b/identidadesComentarios.json")}.getOrDefault(JSONObject());val profiles=runCatching{q("$b/perfisPublicos.json")}.getOrDefault(JSONObject());val frames=runCatching{q("$b/config/commentFrames.json")}.getOrDefault(JSONObject());x.keys().asSequence().mapNotNull{id->x.optJSONObject(id)?.let{n->val uid=n.optString("uid");val i=ids.optJSONObject(uid)?:profiles.optJSONObject(uid)?:JSONObject();val fid=i.optString("molduraComentarioId");val fr=frames.optJSONObject(fid)?:JSONObject();CM(id,i.optString("nome","Leitor MP SCAN"),i.optString("nomeUsuario"),i.optString("foto"),n.optString("texto"),n.optBoolean("spoiler"),CF(fr.optString("nome"),fr.optString("borderColor",fr.optString("bordaCor","#8d2bff")),fr.optString("bgColor",fr.optString("fundoCor","#17171d")),fr.optString("imageUrl",fr.optString("imagem")),fr.optInt("borderWidth",2).coerceIn(1,8)))}}.toList().reversed()}
 suspend fun send(t:String,w:String,c:String,text:String,sp:Boolean,s:AccountSession)=withContext(Dispatchers.IO){q("$b/${path(t,w,c)}.json?auth=${e(s.token)}","POST",JSONObject().put("uid",s.uid).put("data",System.currentTimeMillis()).put("texto",text).put("imagemUrl","").put("spoiler",sp).toString())}}
private fun color(v:String,f:Color)=runCatching{Color(android.graphics.Color.parseColor(v))}.getOrDefault(f)
@Composable fun CommentsSection(type:String,workId:String,chapterId:String="",modifier:Modifier=Modifier){val ctx=LocalContext.current;val api=remember{API()};val store=remember{AccountStore(ctx)};val accounts=remember{AccountRepository()};val scope=rememberCoroutineScope();var session by remember{mutableStateOf(store.session())};var list by remember{mutableStateOf<List<CM>>(emptyList())};var text by remember{mutableStateOf("")};var sp by remember{mutableStateOf(false)};var busy by remember{mutableStateOf(false)};var err by remember{mutableStateOf("")};var login by remember{mutableStateOf(false)}
 LaunchedEffect(Unit){if(session==null){val old=ctx.getSharedPreferences("comments_auth",0);val u=old.getString("u","").orEmpty();val t=old.getString("t","").orEmpty();if(u.isNotBlank()&&t.isNotBlank()){AccountSession(u,"",t).also{store.save(it);session=it}}}}
 suspend fun load(){busy=true;runCatching{api.list(type,workId,chapterId)}.onSuccess{list=it;err=""}.onFailure{err="Sem internet para carregar os comentários."};busy=false};LaunchedEffect(type,workId,chapterId){load()};if(login)LD({login=false}){e,p->scope.launch{runCatching{accounts.signIn(e,p)}.onSuccess{session=it;store.save(it);login=false}.onFailure{err=it.message?:"Não foi possível entrar."}}}
 Column(modifier){Text(if(type=="obra")"Comentários da obra" else "Comentários do capítulo",fontWeight=FontWeight.Black,style=MaterialTheme.typography.headlineSmall);Text("Perfil, avatar e moldura sincronizados com o site",color=MpMuted);Spacer(Modifier.height(10.dp));Surface(color=MpSurface,shape=RoundedCornerShape(18.dp),border=BorderStroke(1.dp,MpLine)){Column(Modifier.padding(14.dp)){if(session==null){Text("Entre com sua conta para comentar.",color=MpMuted);Button({login=true},Modifier.fillMaxWidth().padding(top=8.dp)){Text("Entrar para comentar")}}else{OutlinedTextField(text,{text=it.take(3000)},Modifier.fillMaxWidth(),label={Text("Escreva um comentário…")},minLines=3);Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically){FilterChip(sp,{sp=!sp},{Text(if(sp)"⚠ Spoiler marcado" else "Marcar spoiler")});Spacer(Modifier.weight(1f));Button({scope.launch{busy=true;runCatching{api.send(type,workId,chapterId,text.trim(),sp,session!!)}.onSuccess{text="";sp=false;load()}.onFailure{err="Não foi possível publicar."};busy=false}},enabled=text.isNotBlank()&&!busy){Text("Enviar")}}}}};if(busy)LinearProgressIndicator(Modifier.fillMaxWidth().padding(top=8.dp));if(err.isNotBlank())Text(err,color=MaterialTheme.colorScheme.error,modifier=Modifier.padding(top=8.dp));if(!busy&&list.isEmpty()&&err.isBlank())Text("Ainda não há comentários.",color=MpMuted,modifier=Modifier.padding(14.dp));list.forEach{Card(it)}}}
@Composable private fun Card(x:CM){var show by remember(x.id){mutableStateOf(!x.spoiler)};val bc=color(x.frame.color,MpAccent);val bg=color(x.frame.background,MpSurface);Surface(Modifier.fillMaxWidth().padding(top=10.dp),color=bg,shape=RoundedCornerShape(18.dp),border=BorderStroke(x.frame.width.dp,bc)){Box{if(x.frame.image.isNotBlank())AsyncImage(x.frame.image,null,Modifier.matchParentSize());Column(Modifier.padding(14.dp)){Row(verticalAlignment=Alignment.CenterVertically){Surface(Modifier.size(42.dp),shape=RoundedCornerShape(14.dp),color=MpSurface2,border=BorderStroke(1.dp,bc)){if(x.photo.isNotBlank())AsyncImage(x.photo,null,Modifier.fillMaxSize())else Box(Modifier.fillMaxSize(),contentAlignment=Alignment.Center){Text(x.name.take(1).uppercase(),fontWeight=FontWeight.Black)}};Column(Modifier.padding(start=10.dp)){Text(x.name,fontWeight=FontWeight.Bold);if(x.username.isNotBlank())Text("@${x.username.removePrefix("@")}",color=MpMuted,style=MaterialTheme.typography.labelSmall);if(x.frame.name.isNotBlank())Text("✦ ${x.frame.name}",color=bc,style=MaterialTheme.typography.labelSmall)}};if(x.spoiler&&!show)Text("⚠ Spoiler — toque para revelar",color=MpMuted,modifier=Modifier.padding(top=10.dp).clickable{show=true})else Text(x.text.ifBlank{"Comentário sem texto."},modifier=Modifier.padding(top=10.dp))}}}}
@Composable private fun LD(close:()->Unit,go:(String,String)->Unit){var e by remember{mutableStateOf("")};var p by remember{mutableStateOf("")};AlertDialog(onDismissRequest=close,title={Text("Entrar na MP SCAN")},text={Column{OutlinedTextField(e,{e=it},label={Text("E-mail")});OutlinedTextField(p,{p=it},label={Text("Senha")},visualTransformation=PasswordVisualTransformation())}},confirmButton={Button({go(e,p)},enabled=e.isNotBlank()&&p.isNotBlank()){Text("Entrar")}},dismissButton={TextButton(close){Text("Cancelar")}})}