package online.mpscan.app.ui
import android.content.Context
import androidx.compose.foundation.*
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.*
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.PasswordVisualTransformation
import androidx.compose.ui.unit.dp
import kotlinx.coroutines.*
import online.mpscan.app.ui.theme.*
import org.json.JSONObject
import java.net.*
private data class CS(val uid:String,val token:String)
private data class CC(val id:String,val name:String,val text:String,val spoiler:Boolean)
private class CA(c:Context){val p=c.getSharedPreferences("comments_auth",0);fun get()=p.getString("u",null)?.let{u->p.getString("t",null)?.let{CS(u,it)}};fun put(s:CS)=p.edit().putString("u",s.uid).putString("t",s.token).apply()}
private class CR{val b="https://nnnsss-23f2f-default-rtdb.firebaseio.com";val k="AIzaSyAbpqQIxWuEnFolv3lNjNDoPKTGm0mtrxU";fun e(v:String)=URLEncoder.encode(v,"UTF-8");fun path(t:String,w:String,c:String)=if(t=="obra")"comentariosV1/obra/${e(w)}" else "comentariosV1/capitulo/${e(w)}/${e(c)}"
 fun q(url:String,m:String="GET",body:String?=null):JSONObject{val x=URL(url).openConnection() as HttpURLConnection;x.requestMethod=m;x.connectTimeout=15000;x.readTimeout=25000;x.setRequestProperty("Content-Type","application/json");if(body!=null){x.doOutput=true;x.outputStream.use{it.write(body.toByteArray())}};val ok=x.responseCode in 200..299;val s=(if(ok)x.inputStream else x.errorStream)?.bufferedReader()?.use{it.readText()}.orEmpty();x.disconnect();if(!ok)error(if("INVALID_PASSWORD" in s||"EMAIL_NOT_FOUND" in s)"E-mail ou senha incorretos." else "Não foi possível conectar.");return if(s.isBlank()||s=="null")JSONObject()else JSONObject(s)}
 suspend fun login(e:String,p:String)=withContext(Dispatchers.IO){val x=q("https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=$k","POST",JSONObject().put("email",e).put("password",p).put("returnSecureToken",true).toString());CS(x.getString("localId"),x.getString("idToken"))}
 suspend fun list(t:String,w:String,c:String)=withContext(Dispatchers.IO){val x=q("$b/${path(t,w,c)}.json");val ids=runCatching{q("$b/identidadesComentarios.json")}.getOrDefault(JSONObject());x.keys().asSequence().mapNotNull{id->x.optJSONObject(id)?.let{n->val p=ids.optJSONObject(n.optString("uid"));CC(id,p?.optString("nome")?.takeIf{it.isNotBlank()}?:p?.optString("nomeUsuario")?.takeIf{it.isNotBlank()}?:"Leitor MP SCAN",n.optString("texto"),n.optBoolean("spoiler"))}}.toList().reversed()}
 suspend fun send(t:String,w:String,c:String,text:String,sp:Boolean,s:CS)=withContext(Dispatchers.IO){q("$b/${path(t,w,c)}.json?auth=${e(s.token)}","POST",JSONObject().put("uid",s.uid).put("data",System.currentTimeMillis()).put("texto",text).put("imagemUrl","").put("spoiler",sp).toString())}}
@Composable fun CommentsSection(type:String,workId:String,chapterId:String="",modifier:Modifier=Modifier){val ctx=LocalContext.current;val api=remember{CR()};val auth=remember{CA(ctx)};val scope=rememberCoroutineScope();var session by remember{mutableStateOf(auth.get())};var list by remember{mutableStateOf<List<CC>>(emptyList())};var text by remember{mutableStateOf("")};var sp by remember{mutableStateOf(false)};var busy by remember{mutableStateOf(false)};var err by remember{mutableStateOf("")};var login by remember{mutableStateOf(false)}
 suspend fun load(){busy=true;runCatching{api.list(type,workId,chapterId)}.onSuccess{list=it;err=""}.onFailure{err="Sem internet para carregar os comentários."};busy=false};LaunchedEffect(type,workId,chapterId){load()}
 if(login)LD({login=false}){e,p->scope.launch{runCatching{api.login(e,p)}.onSuccess{session=it;auth.put(it);login=false}.onFailure{err=it.message?:"Não foi possível entrar."}}}
 Column(modifier){Text(if(type=="obra")"Comentários da obra" else "Comentários do capítulo",fontWeight=FontWeight.Black,style=MaterialTheme.typography.headlineSmall);Text("Disponível somente com internet",color=MpMuted);Spacer(Modifier.height(10.dp));Surface(color=MpSurface,shape=RoundedCornerShape(18.dp),border=BorderStroke(1.dp,MpLine)){Column(Modifier.padding(14.dp)){if(session==null){Text("Entre com sua conta para comentar.",color=MpMuted);Button({login=true},Modifier.fillMaxWidth().padding(top=8.dp)){Text("Entrar para comentar")}}else{OutlinedTextField(text,{text=it.take(3000)},Modifier.fillMaxWidth(),label={Text("Escreva um comentário…")},minLines=3);Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically){FilterChip(sp,{sp=!sp},{Text(if(sp)"⚠ Spoiler marcado" else "Marcar spoiler")});Spacer(Modifier.weight(1f));Button({scope.launch{busy=true;runCatching{api.send(type,workId,chapterId,text.trim(),sp,session!!)}.onSuccess{text="";sp=false;load()}.onFailure{err="Não foi possível publicar."};busy=false}},enabled=text.isNotBlank()&&!busy){Text("Enviar")}}}}};if(busy)LinearProgressIndicator(Modifier.fillMaxWidth().padding(top=8.dp));if(err.isNotBlank())Text(err,color=MaterialTheme.colorScheme.error,modifier=Modifier.padding(top=8.dp));if(!busy&&list.isEmpty()&&err.isBlank())Text("Ainda não há comentários.",color=MpMuted,modifier=Modifier.padding(14.dp));list.forEach{Card(it)}}}
@Composable private fun Card(x:CC){var show by remember(x.id){mutableStateOf(!x.spoiler)};Surface(Modifier.fillMaxWidth().padding(top=9.dp),color=MpSurface,shape=RoundedCornerShape(16.dp),border=BorderStroke(1.dp,MpLine)){Column(Modifier.padding(14.dp)){Text(x.name,fontWeight=FontWeight.Bold);if(x.spoiler&&!show)Text("⚠ Spoiler — toque para revelar",color=MpMuted,modifier=Modifier.padding(top=8.dp).clickable{show=true})else Text(x.text.ifBlank{"Comentário sem texto."},modifier=Modifier.padding(top=8.dp))}}}
@Composable private fun LD(close:()->Unit,go:(String,String)->Unit){var e by remember{mutableStateOf("")};var p by remember{mutableStateOf("")};AlertDialog(onDismissRequest=close,title={Text("Entrar para comentar")},text={Column{OutlinedTextField(e,{e=it},label={Text("E-mail")});OutlinedTextField(p,{p=it},label={Text("Senha")},visualTransformation=PasswordVisualTransformation())}},confirmButton={Button({go(e,p)},enabled=e.isNotBlank()&&p.isNotBlank()){Text("Entrar")}},dismissButton={TextButton(close){Text("Cancelar")}})}